### PR TITLE
Word wrap fix: correctly wrap content and prevent vertical overflow

### PR DESCRIPTION
**Pull request by MTzukanov**
https://github.com/tagetik/tagetik-2017-spreadsheet/issues/66

This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/546)

### CODE REVIEW

**Comment by MTzukanov** [comment]
For some reason screenshots are not the same when running from local machine or on team city. Could not properly update the screenshots, if I will not be able to finish this: the only thing that is missing is proper screenshots for older tests where overflow looks correct now.

**Comment by rogozinds** [comment]
Reviewed 13 of 13 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/546)*

**Comment by rogozinds** [comment]
Needs rebasing and fixing build.

**Comment by alvarezguille** [comment]
Rebased and fixed tests in #570

**Pull request closed without merging**
