### PR TITLE
Load filters and tables from Workbook

### PR DESCRIPTION
**Pull request by MTzukanov**
https://github.com/tagetik/tagetik-2017-spreadsheet/issues/1

Related:
https://github.com/vaadin/spreadsheet/issues/369

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/549)

### CODE REVIEW

**Comment by rogozinds** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/ColumnFiltersTest.java, line 53 at r3](https://reviewable.io:443/reviews/vaadin/spreadsheet/549#-KlIGMBwv_E0zB9KN3by:-KlIGMBwv_E0zB9KN3bz:b98evx5) ([raw file](https://github.com/vaadin/spreadsheet/blob/372b199630a9baad5b34f6f22399838f2b93bac9/vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/ColumnFiltersTest.java#L53)):*
> ```Java
>         spreadsheet = new Spreadsheet(workbook);
>     }
> ```

This tests pass only if they are executed in this order. Try to comment the first test and you will see that the second is not passing.
The reason is that you are using iterator().next(), and it doesn't provide any guarantee what the order is. 

---

*[vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/ColumnFiltersTest.java, line 71 at r3](https://reviewable.io:443/reviews/vaadin/spreadsheet/549#-KlIJFnDjtwiHbygfMYu:-KlIJFnDjtwiHbygfMYv:b-ymbga8) ([raw file](https://github.com/vaadin/spreadsheet/blob/372b199630a9baad5b34f6f22399838f2b93bac9/vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/ColumnFiltersTest.java#L71)):*
> ```Java
> 
>         assertNotNull(spreadsheet.getTables());
>         assertEquals(2, spreadsheet.getTables().size());
> ```

Apparently it should be changed to (Or something smarter).
forEach(SpreadsheetTable table) {
   if(table.equals(ctTable) {
   // do your assert
   }
}

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/549)*

**Comment by MTzukanov** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/ColumnFiltersTest.java, line 53 at r3](https://reviewable.io:443/reviews/vaadin/spreadsheet/549#-KlIGMBwv_E0zB9KN3by:-KlIOzcgpfH_Gvmw_eKX:b951jr7) ([raw file](https://github.com/vaadin/spreadsheet/blob/372b199630a9baad5b34f6f22399838f2b93bac9/vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/ColumnFiltersTest.java#L53)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

This tests pass only if they are executed in this order. Try to comment the first test and you will see that the second is not passing.
The reason is that you are using iterator().next(), and it doesn't provide any guarantee what the order is. 
</blockquote></details>

Good catch! new patch is coming

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/549)*

**Comment by rogozinds** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetFactory.java, line 421 at r3](https://reviewable.io:443/reviews/vaadin/spreadsheet/549#-KlIQBNVzNsNyZjYdthS:-KlIQBNWrMfV4y6qU4IG:b-japdp1) ([raw file](https://github.com/vaadin/spreadsheet/blob/372b199630a9baad5b34f6f22399838f2b93bac9/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetFactory.java#L421)):*
> loadSheetTables
The tables are loaded, but there is no highlighting in the filter, that it's applied.
When you select the filter values manually there is this  blue underline in the filter cell header.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetFactory.java, line 421 at r3](https://reviewable.io:443/reviews/vaadin/spreadsheet/549#-KlITJuWhYaeC5wLc9dI:-KlITJuXQJbMIn7mOq0X:bvoa91t) ([raw file](https://github.com/vaadin/spreadsheet/blob/372b199630a9baad5b34f6f22399838f2b93bac9/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetFactory.java#L421)):*
> loadSheetTables
IT seems that if you have auto filter and if you create a table manually, filters on table just don't work. I can show you the example here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/549)*

**Comment by rogozinds** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r4, 2 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/549#-:-KlJ3UbSGKPULFzP2Z9C:bnfp4nl)*

**Comment by rogozinds** [comment]
Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/549)*

**Pull request merged**
