### PR TITLE
Spreadsheet charts unable to open file containing a multilevel chart referring to an area with grouped columns

### PR DESCRIPTION
**Pull request by samsontesfay**
Trying to open an excel file containing a multi level categoris chart referring to an area with a grouped column generates NoSuchElementException.

[Here is a sample file](https://github.com/vaadin/spreadsheet/files/1475850/MultilevelCategoriesWithGroupedColumn.zip)

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/636)

### CODE REVIEW

**Comment by alvarezguille** [comment]
There was a change with the organization CLI and it needs to be signed again by @tepi , @kiaruska and @MTzukanov

**Comment by alexberazouski** [comment]
Reviewed 9 of 9 files at r1.
Review status: 7 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/636)*

**Comment by alexberazouski** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/636#-:-L-WGHAKQcqEzmXRNd8h:bnfp4nl)*

**Comment by alexberazouski** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/636)*

**Pull request merged**
