### PR TITLE
fix for issue #602

### PR DESCRIPTION
**Pull request by ianscriven**
- detect date and time values entered by the user and store them as the correct numeric representations

When the user enters a date or a time, instead of being detected and converted/stored as a numeric cell, it is currently just stored as a string. This fix uses a process similar to how percentages are currently handled to detect these values and convert/store them correctly. Doesn't support a huge number of date/time formats, but is a good starting point.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/608)

### CODE REVIEW

**Comment by ianscriven** [comment]
rebased

**Comment by ianscriven** [comment]
rebased

**Comment by ianscriven** [comment]
I don't see how this change could possibly affect the test that failed, but I'm also unable to run those tests locally. Can anyone help out?

**Comment by ianscriven** [comment]
rebased, tests now passing

**Comment by dancsikpeter** [comment]
Hi,
As i see in SpreadsheetUtil#parseNumber(Cell, String, Locale), a NoSuchMethodException is always thrown when the cell has a dataFormatString. As a result the method falls back to locale based parsing instead of cell based parsing, and in my case that returns null.

The CustomDataFormatter class doesn't have a "getFormat" declared method, the super class has it. So i would use DataFormatter.class.getDeclaredMethod("getFormat", Cell.class) to retreive the method.
After that fix the 'parsed' local variable will be an instance of Date, and a Date -> Number conversion must be implemented to determine the return value.

**Comment by alvarezguille** [comment]
Closing this stale PR, sorry it was overlooked for a long while, please rebase and reopen if still valid

**Pull request closed without merging**
