### PR TITLE
Porting PR 548, Tagetik task 1

### PR DESCRIPTION
**Pull request by MTzukanov**
https://github.com/vaadin/spreadsheet/pull/548

https://github.com/tagetik/tagetik-2017-spreadsheet/issues/55

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/555)

### CODE REVIEW

**Comment by rogozinds** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3, 9 of 12 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/555#-:-KlbrPx-hzicC-o7k_BX:bnfp4nl)*

**Comment by rogozinds** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/555#-:-Klbrbp5crk-SVkFPIrB:bnfp4nl)*

**Comment by rogozinds** [comment]
Reviewed 1 of 12 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/555)*

**Comment by alvarezguille** [comment]
This is not a port of #548. It's porting #549 and #498 to master

**Pull request merged**
