### PR TITLE
fix for #651

### PR DESCRIPTION
**Pull request by ianscriven**
see #651 

Fixes the issue by reversing the iteration order when updating cells (so top to bottom, right to left).

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/654)

### CODE REVIEW

**Comment by WoozyG** [comment]
This is indeed the correct fix, but there are two places it is needed - two implementations of the batch processor functional interface in CellValueManager.

I have both plus a unit test based on the sample file in #651.  I can commit them here or in branch feature/poi-3.17-update-to-release, which I think is close to being merged to master, pending resolution of one last test?  For that matter this change may affect that test.

**Comment by ianscriven** [comment]
Hasn't that branch been merged as part of https://github.com/vaadin/spreadsheet/commit/ed2822ccb9796624d1ca598580207009e75cf4a9? Or are there additional changes?

**Comment by ianscriven** [comment]
Ok. I'm happy for this to be fixed in that branch, and it would make sense to do so if it have an impact on unit tests.

**Comment by WoozyG** [comment]
I've committed the larger change (this one, plus reversing loop order on the other code path, plus this file as a unit test) to the other branch.  Once the last unit test failure is resolved that should get merged back to master.  At that point users could use future release builds with POI versions 3.17 through 4.0.x to pick up further formula evaluation bug fixes (there are two already in 4.0 master that affect some Vaadin unit tests).

**Comment by WoozyG** [comment]
I checked in the change, but something happened with the unit test run - all the PhantomJS screenshot comparison tests failed for some reason.  Vaadin folks will have to tell us what happened there, TeamCity guest access doesn't have enough details.

**Comment by alvarezguille** [comment]
This is now addressed in #701, let's review and merge the solution based on latest POI

**Pull request closed without merging**
