### PR TITLE
Update testbench version and release notes

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/433)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/433)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[assembly/release-notes.html, line 525 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/433#-KXeogPRhMzNwEwxK6Pi:-KXeogPSsEOPrquL-nWO:b-6c0bco) ([raw file](https://github.com/vaadin/spreadsheet/blob/b3d88aadcaebe818a12256c22c4bb3d2dc5bbf52/assembly/release-notes.html#L525)):*
> ```HTML
>     <h2 id="changelog">Change log for Vaadin Spreadsheet ${project.version}</h2>
>     <ul>
>         <li>Added Vaadin 8 and Java 8 support.</li>
> ```

Sounds a bit like it supports both FW7 and FW8

Could also mention browser support, at least dropped browsers

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/433)*

**Comment by rogozinds** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[assembly/release-notes.html, line 525 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/433#-KXeogPRhMzNwEwxK6Pi:-KXfMC760Erftn505TJK:b-896fix) ([raw file](https://github.com/vaadin/spreadsheet/blob/b3d88aadcaebe818a12256c22c4bb3d2dc5bbf52/assembly/release-notes.html#L525)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Sounds a bit like it supports both FW7 and FW8

Could also mention browser support, at least dropped browsers
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/433)*

**Comment by Artur-** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[assembly/release-notes.html, line 525 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/433#-KXeogPRhMzNwEwxK6Pi:-KXfMRlE_J86qzFgohVW:b3bcrxc) ([raw file](https://github.com/vaadin/spreadsheet/blob/b3d88aadcaebe818a12256c22c4bb3d2dc5bbf52/assembly/release-notes.html#L525)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

How about "Requires Vaadin Framework 8 and Java 8"? Neither Framework 7 nor Java 7 will work

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/433)*

**Comment by rogozinds** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[assembly/release-notes.html, line 525 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/433#-KXeogPRhMzNwEwxK6Pi:-KXfOQgHVrgLb9BuDlR-:b-896fix) ([raw file](https://github.com/vaadin/spreadsheet/blob/b3d88aadcaebe818a12256c22c4bb3d2dc5bbf52/assembly/release-notes.html#L525)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

How about "Requires Vaadin Framework 8 and Java 8"? Neither Framework 7 nor Java 7 will work
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/433)*

**Comment by Artur-** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/433)*

**Comment by Artur-** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/433)*

**Comment by alvarezguille** [comment]
@rogozinds was this already included in #434

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/433)*

**Pull request merged**
