### PR TITLE
Named range reference feature

### PR DESCRIPTION
**Pull request by MTzukanov**
(Lowest priority in review)

https://github.com/tagetik/tagetik-2017-spreadsheet/issues/8

This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/552)

### CODE REVIEW

**Comment by MTzukanov** [comment]
This is ready for review. Requires screenshot update for InteractionTBTest-openFileWithNotSuportedForumla_noExceptionRaised_noChart_PhantomJS_unparsedFormula.png (all browsers).

**Comment by MTzukanov** [comment]
There is one commit by Leszek, who has not signed the agreement, see what you can do about it.

**Comment by alvarezguille** [comment]
Did an initial check of this PR and got the following comments:
* is it possible to get all committers to sign CLA? lladnik is still missing
* changes done in `_spreadsheet-valo.scss` are needed in `_spreadsheet-legacy.scss` for compatibility with pre-valo themes
* what should the behavior be with non-continuous range? currently it's not selecting
* is it possible to keep the empty selection without adding the empty string option?

**Comment by alessandroguarascio** [comment]
> is it possible to get all committers to sign CLA? lladnik is still missing
I think lladnik is a Vaadin Employee, are you able to contact him and ask for signature? We never worked directly with him.

> changes done in _spreadsheet-valo.scss are needed in _spreadsheet-legacy.scss for compatibility with pre-valo themes
Done

> what should the behavior be with non-continuous range? currently it's not selecting
Named range functionality in case of non-contiguous ranges was just a stretch requirement from Tagetik point of view (as stated in the comments of the original task). So we let Michael free to decide where to include it or not. From our point of view we don't need this feature, at least not in this phase.

> is it possible to keep the empty selection without adding the empty string option?
What should be the behaviour? The Excel behaviour is quite complex: you must delete manually the range name from the text box. Once done so, Excel removes the selection from the named range and selects again the cell that was previously selected. Spreadsheet does not allow to remove manually such names... From our point of view the actual behaviour could be a good compromise, but... you have to tell.

**Comment by alvarezguille** [comment]
All changes are now included in #561, please subscribe to that PR for updated

**Pull request closed without merging**
