### PR TITLE
Fixes for #461

### PR DESCRIPTION
**Pull request by WoozyG**
this change addresses all but point 4 (a minor one) in issue #461, and gets things ready to add table style support as well ( #529 ), by introducing the `IncrementalStyleBuilder` class to break out common Excel to CSS style conversion code.

If it looks rather involved, it is.  It updates to POI 3.17-beta1, required for some of the conditional formatting logic encapsulation, and delegates all that to POI.  Cell conditional formatting CSS rule index values are deterministic based on conditional format index, rule index within that, and the "style type" of the formatting style - base formatting (foreground/background, etc.) and border part.  No more need to track mappings for rules to cells, just evaluate rules and calculate the ID when needed.

Table styles will use very similar logic, and get called from the same locations.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/595)

### CODE REVIEW

**Comment by WoozyG** [comment]
[This Microsoft Sample Workbook](http://download.microsoft.com/download/1/6/F/16F701E9-63BA-48D3-8B48-096F9288F443/AF010235700_en-us_cfsamples_af010235700.xlsx) has the following behavior now in the demo app (mvn jetty:run):

## Sheets that work as expected:
Products1
Products2
Book tour
Grades (except cell value formats that include static text, known POI limitation)
Customers1
Banded rows
Compare to totals - except negative number formatting (I have another PR coming for that)
Products 3

## Sheets that have missing pieces or POI limitations/bugs:
Grades - no table styles (yet, PR coming)
Quarters - no icon-set support in Vaadin CSS yet, could be added
Bike Rating - no icon-set support
FY months - no icon-set support
Regional sales - no icon-set support, table footer uses unimplemented function: SUBTOTAL with 'exclude hidden values' option
Mountains - no data bar support in Vaadin CSS yet, could be added
Category sales - no gradient scale support in Vaadin CSS yet, could be added
Customers2 - I think there is still a bug in POI's implementation of COUNTIFS despite recent work on it

**Comment by WoozyG** [comment]
I'm having trouble figuring out how to run the TestBench tests locally, as they are configured for an internal Vaadin grid.  I suspect these failures are due to improved conditional formatting handling in general, but there could be some cases I've not encountered yet with our own internal tests, or other changes I missed that I should copy to this PR.  Any feedback on the test failures and/or tips on running them myself would be appreciated, to help move the discussion along for this PR.

**Comment by WoozyG** [comment]
I'd like to view the screenshot differences reported for this PR, but I'm at this point in debugging my TestBench setup for this project:

I can add a hosts entry in Windows to redirect the hard-coded  hub name "tb3-hub.intra.itmill.com" to localhost, and run a grid server and node locally.  I have that working.  I have the webdrivers for the various browsers installed in my system path.  However, the tests still fail.  The hub server says it got requests like this:

    09:46:00.510 INFO - Got a request to create a new session: Capabilities [{ensureCleanSession=true, ie.ensureCleanSession=true, enablePersistentHover=false, build=192.168.1.19 / Tue Aug 15 09:45:59 PDT 2017, requireWindowFocus=true, name=com.vaadin.addon.spreadsheet.test.BordersWithHiddenColumnsAndRowsTest.test[Windows_InternetExplorer_11], browserName=internet explorer, project=Vaadin Spreadsheet, version=11, platform=WINDOWS}]

and the Vaadin test fails with this message:

    Browser startup for Capabilities [{ensureCleanSession=true, ie.ensureCleanSession=true, enablePersistentHover=false, build=192.168.1.19 / Tue Aug 15 09:45:59 PDT 2017, requireWindowFocus=true, name=com.vaadin.addon.spreadsheet.test.BordersWithHiddenColumnsAndRowsTest.test[Windows_InternetExplorer_11], browserName=internet explorer, project=Vaadin Spreadsheet, version=11, platform=WINDOWS}] failed on attempt 1: Error forwarding the new session cannot find : Capabilities [{ensureCleanSession=true, ie.ensureCleanSession=true, enablePersistentHover=false, build=192.168.1.19 / Tue Aug 15 09:45:59 PDT 2017, requireWindowFocus=true, name=com.vaadin.addon.spreadsheet.test.BordersWithHiddenColumnsAndRowsTest.test[Windows_InternetExplorer_11], browserName=internet explorer, project=Vaadin Spreadsheet, version=11, platform=WINDOWS}]
    Command duration or timeout: 130 milliseconds
    Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
    System info: host: 'GREG-LAP1', ip: '192.168.1.19', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_60'
    Driver info: driver.version: SetupDriver

The hub reports a single node, and shows a web driver for these browser settings as registered:

    {seleniumProtocol=WebDriver, browserName=internet explorer, maxInstances=1, platform=WIN10}

According to the Selenium JavaDoc for the platform enum, WINDOWS is a generic value used only for requests when any version of Windows is acceptable, so I have no idea why the hub is failing to use the regisered WIN10 browser.

**Comment by WoozyG** [comment]
Some more tests pass.  Some of the failures, at least in IE 11, which I can now run locally, have screenshots that differ only in the shading of the top section of the test page window - the test controls appear covered by a non-clickable transparent layer in the baseline screenshots, but in my tests they are not.  Spreadsheet cell borders etc. look exactly the same, so functionally those tests should pass.  Not sure where the highlighting difference outside the spreadsheet component comes from.

Other failures appear to be due to some POI changes in cell value rendering, which I'm currently investigating.  I fixed a couple of POI bugs referenced by comments in Vaadin code, so perhaps I need to go remove the Vaadin workarounds for those bugs.

**Comment by WoozyG** [comment]
This last commit has only 4 failures.  One, I'm not sure what to do with, as it runs too slow in Chrome for me to test (with the debug window open) it times out processing the server response.

CopyPasteCellsTest.spreadsheetHandlerOnPaste_PasteCells_SmallServerJsonResponse

The other 3 appear to be due to a bug in the POI conditional format logic I implemented - I was erroneously assuming non-existent cells couldn't have conditional formatting, but these tests prove otherwise.  Failure of lateral creative thinking on my part there.  I will be updating POI and adding a unit test based on 

conditional_formatting_with_formula_on_second_sheet.xlsx

unfortunately this will only be in POI nightlies until either 3.17 or 3.17-beta2 is released.  Haven't seen any discussion yet about the need for a beta2 vs. a final 3.17 release, but end of summer was the target for 3.17, and the bug database and user lists have been quiet.

At this point, I need some Vaadin guidance about how you want to proceed with CopyPasteCellsTest.spreadsheetHandlerOnPaste_PasteCells_SmallServerJsonResponse and failures due to POI awaiting a POI fix.

**Comment by WoozyG** [comment]
Commited the POI fix for conditional formatting of undefined cells in POI revision [r1805245](http://svn.apache.org/viewvc?rev=1805245&view=rev), which will be in 3.17.  I used one of the Vaadin test files as the basis for the POI unit test, hope that's OK.

**Comment by WoozyG** [comment]
POI 3.17 RC1 has been built and is now in the test and comment pre-release phase.

**Comment by vlukashov** [comment]
Hi @WoozyG! First of all, thank you for taking the time to contribute!
I have an idea why the

`CopyPasteCellsTest.spreadsheetHandlerOnPaste_PasteCells_SmallServerJsonResponse`

test fails. It's not directly related to upgrading POI to 3.17 -- it is caused by some changes in this PR. 

Here are the steps to reproduce the issue with a local jetty:run:
 - start a local jetty in the vaadin-spreadsheet project
 - open the demo app in the debug mode: http://localhost:9998/SpreadsheetDemoUI?debug
 - click at 'Create new' to generate a blank spreadsheet
 - enter values in a few cells
 - see that after modifying every single cell, **all** cells in the spreadsheet get refreshed from the server (even if they have not changed)

vaadin-spreadsheet-all-cells-updated

The failing test has a spreadsheet with 100000 cells. One of the test actions modifies a few cells in the spreadsheet and that causes a full refresh (which takes a veeery long time). Likely, that's what caused timeouts when you tried to investigate.

**Comment by WoozyG** [comment]
Hmm.  The previous behavior, while smaller, was in some cases too small,
and failed to update some cells whose calculated value should have changed,
as verified by performing the same actions in Excel.  I'll look through our
bug reports to see if I can find an example.  I believe it had to do with a
deep enough formula dependency graph, but I'm not sure, I saw it late last
year some time.

Any insights as to what exactly changed would be appreciated, but I'll keep
chipping away at it.  This is the code we are currently using in-house.

**Comment by vlukashov** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/ConditionalFormatter.java, line 197 at r4](https://reviewable.io:443/reviews/vaadin/spreadsheet/595#-Ksm75u_WTFgM2xvy6ge:-Ksm75u_WTFgM2xvy6gf:b-r9nmit) ([raw file](https://github.com/vaadin/spreadsheet/blob/e1410e3ee8456dbc7d320bc55e85afabf36a490f/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/ConditionalFormatter.java#L197)):*
> ```Java
>         }
> 
>         cellToCssIndex.clear();
> ```

Even though the `cellToCssIndex` map is cleared here, it gets re-populated with all the same values when marked cells' values are updated later on:

```
com.vaadin.addon.spreadsheet.ConditionalFormatter.getCellFormattingIndexInternal(ConditionalFormatter.java:244)
com.vaadin.addon.spreadsheet.ConditionalFormatter.getCellFormattingIndex(ConditionalFormatter.java:229)
com.vaadin.addon.spreadsheet.CellValueManager.createCellDataForCell(CellValueManager.java:328)
com.vaadin.addon.spreadsheet.CellValueManager.updateMarkedCellValues(CellValueManager.java:1161)
com.vaadin.addon.spreadsheet.Spreadsheet.updateMarkedCells(Spreadsheet.java:1588)
```

Effectively that means that every cell ever added into the map is never removed, so the map includes all cells in the spreadsheet, and they are all marked as updated on any single cell update.

Please check the logic of adding / removing values into the `cellToCssIndex` map and try to find a way to clear it correctly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/595)*

**Comment by WoozyG** [comment]
Thank you, I'll start there in my morning.

**Comment by WoozyG** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/ConditionalFormatter.java, line 197 at r4](https://reviewable.io:443/reviews/vaadin/spreadsheet/595#-Ksm75u_WTFgM2xvy6ge:-KspUdLus9Uph4IHeMGG:b24b8zj) ([raw file](https://github.com/vaadin/spreadsheet/blob/df5c604e2c9113b0e71ab1a7c50694e26dfdae13/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/ConditionalFormatter.java#L197)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Even though the `cellToCssIndex` map is cleared here, it gets re-populated with all the same values when marked cells' values are updated later on:

```
com.vaadin.addon.spreadsheet.ConditionalFormatter.getCellFormattingIndexInternal(ConditionalFormatter.java:244)
com.vaadin.addon.spreadsheet.ConditionalFormatter.getCellFormattingIndex(ConditionalFormatter.java:229)
com.vaadin.addon.spreadsheet.CellValueManager.createCellDataForCell(CellValueManager.java:328)
com.vaadin.addon.spreadsheet.CellValueManager.updateMarkedCellValues(CellValueManager.java:1161)
com.vaadin.addon.spreadsheet.Spreadsheet.updateMarkedCells(Spreadsheet.java:1588)
```

Effectively that means that every cell ever added into the map is never removed, so the map includes all cells in the spreadsheet, and they are all marked as updated on any single cell update.

Please check the logic of adding / removing values into the `cellToCssIndex` map and try to find a way to clear it correctly.
</blockquote></details>

addressed this and a few other things in today's commits.  See the commit messages for details.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/595)*

**Comment by WoozyG** [comment]
Looks like that last commit fixed things up - tests pass except the one that requires the POI bug fix.  3.17 should go final later this week/early next, we're in final stages of testing and voting.

I also got in the fix for another POI bug filed by a Vaadin dev, [#61468](https://bz.apache.org/bugzilla/show_bug.cgi?id=61468).

Once that is final, I can make one more commit to this branch to switch to POI 3.17 dependency, and all tests should pass, and we can discuss whether Vaadin can take this or not.

**Comment by vlukashov** [comment]
Thanks for fixing the POI issue which I've reported! We are looking to upgrade to 3.17 soon after it becomes stable.

---

Reviewed 3 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 2 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/CellValueManager.java, line 1158 at r5](https://reviewable.io:443/reviews/vaadin/spreadsheet/595#-KswxCEQqk_PuCwW0s7F:-KswxCEQqk_PuCwW0s7G:b-bkide8) ([raw file](https://github.com/vaadin/spreadsheet/blob/f51797552beaee9ea7e19bb76a0f8c67117f3120/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/CellValueManager.java#L1158)):*
> ```Java
>         // might have changed. also make sure all marked cells are updated
>         Iterator<Row> rows = sheet.rowIterator();
>     	spreadsheet.getConditionalFormatter().startEvaluationRun();
> ```

This is a working way to get some caching benefits and avoid recalculating styles for the same cells while going through the loop.
Since it is good for performance I'd like to keep this functionality.

However, the current implementation adds an internal state to `conditionalFormatter` which developers should keep in mind: one needs to remember to call `startEvaluationRun()` and `endEvaluationRun()` in all correct places (and also take into account possible exceptions). And this state is write-only: it cannot be queried with any public API. While it works OK for the current use case, I would argue that from the maintenance perspective it's not a good practice.

Can I suggest changing the approach from
```java
ConditionalFormatter formatter = spreadsheet.getConditionalFormatter();
formatter.startEvaluationRun();
try {
    doSomething();
        ... which eventually calls ...
            formatter.getCellFormattingIndex(cell);
} finally {
    formatter.endEvaluationRun();
}
```

into something along the lines of
```java
ConditionalFormatter formatter = spreadsheet.getConditionalFormatter();
IFormattingBatch batch = formatter.createFormattingBatch();
doSomething(batch);
    ... which eventually calls ...
        formatter.getCellFormattingIndex(cell, batch);
```
(i.e. use an external 'batch' object to keep the cache out of the conditional formatter instance)

or maybe into something like
```java
ConditionalFormatter formatter = new CachingConditionalFormatter();
spreadsheet.setConditionalFormatter(formatter);
doSomething();
    ... which eventually calls ...
        formatter.getCellFormattingIndex(cell);
```
(i.e. use keep the cache inside the formatter but create a new conditional formatter instance for each batch of style calculations -- if creating such instances is a cheap operation)
?

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/ConditionalFormatter.java, line 206 at r5](https://reviewable.io:443/reviews/vaadin/spreadsheet/595#-Ksqu0FVlL9qMMrSdmaH:-Ksqu0FVlL9qMMrSdmaI:b4tlhl3) ([raw file](https://github.com/vaadin/spreadsheet/blob/f51797552beaee9ea7e19bb76a0f8c67117f3120/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/ConditionalFormatter.java#L206)):*
> ```Java
> 				Cell cell = spreadsheet.getCell(row, col);
> 				if (cell != null) {
> 					spreadsheet.getCellValueManager().markCellForUpdate(cell);
> ```

The new line `spreadsheet.getCellValueManager().markCellForUpdate(cell);` is not fully equivalent to the old one `spreadsheet.markCellAsUpdated(cell, true);`

```java
void markCellAsUpdated(Cell cell, boolean cellStyleUpdated) {
    valueManager.cellUpdated(cell);
    if (cellStyleUpdated) {
        styler.cellStyleUpdated(cell, true);
    }
}
```

These two actions are now skipped:
 - `spreadsheet.getFormulaEvaluator().notifyUpdateCell(cell);`
 - `spreadsheet.getSpreadsheetStyleFactory().cellStyleUpdated(cell, true);`

I did not follow the logic why they are not necessary anymore. Could you please elaborate?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/595#-:-Ksx9qVglN4qwdpdyIO7:b-vwqzq9)*

**Comment by WoozyG** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/CellValueManager.java, line 1158 at r5](https://reviewable.io:443/reviews/vaadin/spreadsheet/595#-KswxCEQqk_PuCwW0s7F:-KszSjgKM0sKTTKGVqUg:b-2mgact) ([raw file](https://github.com/vaadin/spreadsheet/blob/f51797552beaee9ea7e19bb76a0f8c67117f3120/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/CellValueManager.java#L1158)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

This is a working way to get some caching benefits and avoid recalculating styles for the same cells while going through the loop.
Since it is good for performance I'd like to keep this functionality.

However, the current implementation adds an internal state to `conditionalFormatter` which developers should keep in mind: one needs to remember to call `startEvaluationRun()` and `endEvaluationRun()` in all correct places (and also take into account possible exceptions). And this state is write-only: it cannot be queried with any public API. While it works OK for the current use case, I would argue that from the maintenance perspective it's not a good practice.

Can I suggest changing the approach from
```java
ConditionalFormatter formatter = spreadsheet.getConditionalFormatter();
formatter.startEvaluationRun();
try {
    doSomething();
        ... which eventually calls ...
            formatter.getCellFormattingIndex(cell);
} finally {
    formatter.endEvaluationRun();
}
```

into something along the lines of
```java
ConditionalFormatter formatter = spreadsheet.getConditionalFormatter();
IFormattingBatch batch = formatter.createFormattingBatch();
doSomething(batch);
    ... which eventually calls ...
        formatter.getCellFormattingIndex(cell, batch);
```
(i.e. use an external 'batch' object to keep the cache out of the conditional formatter instance)

or maybe into something like
```java
ConditionalFormatter formatter = new CachingConditionalFormatter();
spreadsheet.setConditionalFormatter(formatter);
doSomething();
    ... which eventually calls ...
        formatter.getCellFormattingIndex(cell);
```
(i.e. use keep the cache inside the formatter but create a new conditional formatter instance for each batch of style calculations -- if creating such instances is a cheap operation)
?
</blockquote></details>

I'm committing a change to take this advice.  I knew it was hacky, I was frustrated at not being able to figure out why the repeated evaluation was also causing side effects I couldn't replicate with a simple unit test in POI.  Makes me think somewhere in this project some code was replacing cell formulas with the text of the formula when the formula failed to evaluate.

The updated version uses a couple of functional interfaces and can be called via simple Lambda wrappers around existing code.  It tests fine for me locally.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/ConditionalFormatter.java, line 206 at r5](https://reviewable.io:443/reviews/vaadin/spreadsheet/595#-Ksqu0FVlL9qMMrSdmaH:-KszTPUG9CxJfgLKAO5k:bnsu3qw) ([raw file](https://github.com/vaadin/spreadsheet/blob/f51797552beaee9ea7e19bb76a0f8c67117f3120/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/ConditionalFormatter.java#L206)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

The new line `spreadsheet.getCellValueManager().markCellForUpdate(cell);` is not fully equivalent to the old one `spreadsheet.markCellAsUpdated(cell, true);`

```java
void markCellAsUpdated(Cell cell, boolean cellStyleUpdated) {
    valueManager.cellUpdated(cell);
    if (cellStyleUpdated) {
        styler.cellStyleUpdated(cell, true);
    }
}
```

These two actions are now skipped:
 - `spreadsheet.getFormulaEvaluator().notifyUpdateCell(cell);`
 - `spreadsheet.getSpreadsheetStyleFactory().cellStyleUpdated(cell, true);`

I did not follow the logic why they are not necessary anymore. Could you please elaborate?
</blockquote></details>

Formulas and cell styles aren't changing, so we don't want to perform extra notifications for no-ops.  Displayed styles are changing, but CellValueManager and the rest of the widget framework treat conditional formatting and cell explicit styling as independent things.  There is no interaction between them beyond the numeric ordering to get the proper CSS override logic in place, so no changes to tell anyone about.

Further, this is really only needed in the case noted in another issue, where the cell used to have conditional formatting applied, but a value changed somewhere, and the formatting no longer applies.  In that case we need to explicitly add the cell to the list of cells to re-send to the client, or the client will keep the old formatting on it.

I'll use this further when I submit my work to implement table styles, as those would be similar to conditional formatting styles (there's an issue I filed with details).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/595)*

**Comment by vlukashov** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/595)*

**Comment by DiegoCardoso** [comment]
Hi @woozyg!

After pushing one commit to fix one issue in Javadoc, I could see that some tests are red. I have opened the excel files for each failed test with the Demo UI on both `master` and your branch and could confirm that they look different. 
Only for `conditional_formatting_with_formula_on_second_sheet.xlsx` I could make look like what we have now by double clicking and clicking out on C10 and D10 cells.
Can you see if you can reproduce this behaviour as well? 

---

Review status: 7 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/595#-:-KtHOd1GmMzO0qd60Y06:b-3iqva1)*

**Comment by WoozyG** [comment]
Yes, 4 tests fail currently.  As I mentioned in a previous comment on the PR, they will pass once POI 3.17 is finalized and this branch can switch dependencies to that version.  The difference is a bug in POI, which I've fixed in 3.17.

I'd hoped 3.17 would be out this week.  That's still a possibility, but there is one ClassLoader issue affecting another dependent Apache project we are still investigating before we can call it final and push it to the Maven repositories.

---

Review status: 7 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/595#-:-KtHUuE4Ct_6FNSAMudR:b-d7psio)*

**Comment by DiegoCardoso** [comment]
I have changed the base branch from `master` to `feature/poi-3.17`. I ignored the failing tests to make it green and merge this PR. When POI 3.17 final is released, we will enable those tests again.

---

Review status: 6 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/595#-:-KtM28Jn-jrF8b64fhtp:bjta4m6)*

**Comment by DiegoCardoso** [comment]
Reviewed 2 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 2 files at r4, 1 of 2 files at r6, 2 of 3 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/595)*

**Pull request merged**
