### PR TITLE
Resolving trac ticket #17725

### PR DESCRIPTION
**Pull request by lucailmartini**
change the MINIMUM_ROW_HEIGHT_FOR_COMPONENTS static field into a non final instance field
added getter and setter to the Spreadsheet class

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/2)

### CODE REVIEW

**Comment by lucailmartini** [comment]
resolve Github issue #245

**Comment by Artur-** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/Spreadsheet.java, line 5040 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/2#-KX6I3BZcGYBKoR1bQxB:-KX6I3BZcGYBKoR1bQxC:bc0ftnu) ([raw file](https://github.com/vaadin/spreadsheet/blob/f814539aaceb22ce976ba0ea9709fb8efa02938e/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/Spreadsheet.java#L5040)):*
> ```Java
>     /***
>      * Set the minimum row heigth in points for the rows that contain custom
>      * components
> ```

Could mention as a warning that if you reduce this, it might cause some components like checkboxes to be cut off

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/2)*

**Comment by lucailmartini** [comment]
Hi @Artur-, I have added the warning message as you requested.
This PR was made when the spreadsheet was at version 1.3.

I see that not it conflicts with the latest master branch (the to be 2.0).
Since we cannot upgrade to 2.0 in a short time, it would be very much appreciated if this change could be backported to 1.3.x version.

**Comment by alvarezguille** [comment]
Some comments regarding the changes: 
* The branch should be rebased
* The changes to the import lines should be reverted
* Regarding adding Mockito dependency, I think it could be avoided if tested with same approach as in SpreadsheetCustomEditorsTest that it’s using TestableUI, it’s worth trying it at least
Once merged the change can be back-ported.

**Pull request closed without merging**
