### PR TITLE
Throw IOException when open strict OOXML files #397

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/442)

### CODE REVIEW

**Comment by alvarezguille** [comment]
*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetFactory.java, line 226 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/442#-KZ1je41DyYZX8ioevEK:-KZ1je41DyYZX8ioevEL:b-hdss45) ([raw file](https://github.com/vaadin/spreadsheet/blob/982ed3cb2ab54015c82e691b698392faadcbfcdd/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetFactory.java#L226)):*
> bug/bug397

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/442)*

**Comment by alvarezguille** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/spreadsheet-overview.asciidoc, line 140 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/442#-KZ1hmBZz8rt7pwaVUkL:-KZ1hmBZz8rt7pwaVUkM:b-q6yulh) ([raw file](https://github.com/vaadin/spreadsheet/blob/982ed3cb2ab54015c82e691b698392faadcbfcdd/documentation/spreadsheet-overview.asciidoc#L140)):*
>See, for details.

is missing something

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/442)*

**Comment by alvarezguille** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetFactory.java, line 230 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/442#-KZ1vj_UjJeg7F34k9ff:-KZ1vj_UjJeg7F34k9fg:beyot17) ([raw file](https://github.com/vaadin/spreadsheet/blob/982ed3cb2ab54015c82e691b698392faadcbfcdd/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetFactory.java#L230)):*
Can we ensure that this exception is only thrown when Strict OOXML is used? Is there any evidence?
If not, can we just wrap the exception? So that the original message is in there.
> IOException(e);

My worry is that it might have a different cause in some situation and we're giving the wrong message

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/442)*

**Comment by rogozinds** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[documentation/spreadsheet-overview.asciidoc, line 140 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/442#-KZ1hmBZz8rt7pwaVUkL:-KZMevBR4-Ks5IVBBFZn:b-896fix) ([raw file](https://github.com/vaadin/spreadsheet/blob/982ed3cb2ab54015c82e691b698392faadcbfcdd/documentation/spreadsheet-overview.asciidoc#L140)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>See, for details.

is missing something
</blockquote></details>

Done.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetFactory.java, line 230 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/442#-KZ1vj_UjJeg7F34k9ff:-KZQWMGyvmUetn0cH5bH:b-896fix) ([raw file](https://github.com/vaadin/spreadsheet/blob/982ed3cb2ab54015c82e691b698392faadcbfcdd/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetFactory.java#L230)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

Can we ensure that this exception is only thrown when Strict OOXML is used? Is there any evidence?
If not, can we just wrap the exception? So that the original message is in there.
> IOException(e);

My worry is that it might have a different cause in some situation and we're giving the wrong message
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/442)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/442)*

**Pull request merged**
