### PR TITLE
fixes issue #190 Spreadsheet filter button autofit

### PR DESCRIPTION
**Pull request by OlliTietavainenVaadin**
Adds space for filter popup button when autofitting columns. Also resizes autofitted columns when
a filter table is added.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/481)

### CODE REVIEW

**Comment by rogozinds** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/Spreadsheet.java, line 1999 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/481#-Kjb_elIjYTJQ0TENB1h:-Kjb_elJdc0DK5TWZ8h7:b-f69bjv) ([raw file](https://github.com/vaadin/spreadsheet/blob/5913312cc8dc1be8f862322103ced9c74c3eb9f8/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/Spreadsheet.java#L1999)):*
>  private Map<CellReference, Integer> autofittedColumnWidths = new HashMap<>();
The values are never removed from the map, so there is a potential memory leak.
If you removing cells, they wont' be garbage collected.
One possible solution is to use WeakMap or to manually remove values from this map.

Map also should be added at the  top of the class ,where all properties are added, otherwise it's hard to find.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/Spreadsheet.java, line 2022 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/481#-KjbaVn2-AhFaj8bztOE:-KjbaVn2-AhFaj8bztOF:b-sq1qhg) ([raw file](https://github.com/vaadin/spreadsheet/blob/5913312cc8dc1be8f862322103ced9c74c3eb9f8/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/Spreadsheet.java#L2022)):*
> // TODO: fetch button width from client side?
What is this TODO, who gonna do it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/481)*

**Comment by OlliTietavainenVaadin** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/Spreadsheet.java, line 1999 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/481#-Kjb_elIjYTJQ0TENB1h:-KjbimBPRKrCGkyN_Wpv:b-tzgrwn) ([raw file](https://github.com/vaadin/spreadsheet/blob/5913312cc8dc1be8f862322103ced9c74c3eb9f8/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/Spreadsheet.java#L1999)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

>  private Map<CellReference, Integer> autofittedColumnWidths = new HashMap<>();
The values are never removed from the map, so there is a potential memory leak.
If you removing cells, they wont' be garbage collected.
One possible solution is to use WeakMap or to manually remove values from this map.

Map also should be added at the  top of the class ,where all properties are added, otherwise it's hard to find.
</blockquote></details>

OK, changed to WeakHashMap and moved to top of file

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/Spreadsheet.java, line 2022 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/481#-KjbaVn2-AhFaj8bztOE:-KjbiZOfxCyZ49_X7fKA:b-2qr1ud) ([raw file](https://github.com/vaadin/spreadsheet/blob/5913312cc8dc1be8f862322103ced9c74c3eb9f8/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/Spreadsheet.java#L2022)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

> // TODO: fetch button width from client side?
What is this TODO, who gonna do it?
</blockquote></details>

OK, removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/481)*

**Comment by alvarezguille** [comment]
I'm not sure if it's part of the same issue but doesn't seem to be working with manual autofit (double click on division between column headers), at leas the part of "also resizes autofitted columns when a filter table is added"

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/481#-:-KjcXS0QbIofmH8Lxsri:bm2lbce)*

**Comment by OlliTietavainenVaadin** [comment]
Can you even do manual autofit in Spreadsheet? Is there some setting you need to enable? I can't at least do it in SpreadsheetDemoUI - I can't even resize the columns manually.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/481#-:-KjhGuIOdPkB5nRiJ5JY:b2naot5)*

**Comment by rogozinds** [comment]
Yes, you can auto resize in SpreadsheetDemoUI. You can either resize by dragging or just double click on the right edge/side of the column

**Comment by OlliTietavainenVaadin** [comment]
Added a fix for button disappearing button on certain overflow situations.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/481#-:-KkGUEeHN79WpEF1klLI:b-o9pwpn)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/481)*

**Pull request merged**
