### PR TITLE
Adjust calls to deprecated POI methods removed in POI 4.0.

### PR DESCRIPTION
**Pull request by WoozyG**
These changes are all 3.17 compatible, and enable downstream users to
drop in 4.0 builds as needed.

This is a way Spreadsheet users can get the conditional formatting fixes
done in 4.0 without further code changes, once this branch is merged
back and released.

Alternatively, a POI 4.0 build could be lobbied for, and this branch
could move up to that version.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/640)

### CODE REVIEW

**Comment by WoozyG** [comment]
Same test failures as #617, fixed in POI master.

**Comment by alexberazouski** [comment]
There is one new test failure in SheetFilterTableTest. Let's do not merge it to the with 3.17 update

---

Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/640#-:-L-lFTmarMZOC7CRfoAM:b-27cpab)*

**Comment by WoozyG** [comment]
I didn't touch any code near that failure, and indeed, that test passes for the build and me except in PhantomJS.  Sounds suspiciously like a bug where PhantomJS isn't updating the DOM when other engines do?  Is there a way to manually check this failure?

**Comment by WoozyG** [comment]
In fact, the second time I ran this test locally, it passed.  Not sure what's going on.

**Comment by alexberazouski** [comment]
Yes, I see. But same test failed after build restart again

---

Review status: 5 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/640#-:-L-pRGFRMwTsM6vKDqYL:bxb3341)*

**Comment by WoozyG** [comment]
The build on Dec. 1, #1063, was the first one with this new test failure.  The only change in that build was in JavaDoc.  That obviously isn't the cause.  None of the later changes affect that test either.  That test passes for me locally.  I suspect some change to the automated test harness that is affecting it. 

That particular test is potentially susceptible to concurrency/timing affects, among other things.

**Comment by WoozyG** [comment]
What happened with this test run?  Looks like all the PhantomJS tests failed due to mismatched screenshots?

**Comment by alvarezguille** [comment]
@WoozyG please reopen if this is still valid

**Pull request closed without merging**
