### PR TITLE
Feature/rmv7 ssdemoui

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/414)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/demoapps/FileDataSource.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/414#-KWrvftxUT-frIgo8VuF:-KWrvftxUT-frIgo8VuG:bsuxo65) ([raw file](https://github.com/vaadin/spreadsheet/blob/fb52db7de7e44637160677cb55688a0b0b968c25/vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/demoapps/FileDataSource.java#L37)):*
> ```Java
>         }
>         catch (IOException e) {
>             System.out.println(e.getMessage());
> ```

handle in a nicer way

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/414)*

**Comment by rogozinds** [comment]
Review status: 0 of 83 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/demoapps/FileDataSource.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/414#-KWrvftxUT-frIgo8VuF:-KX60pD-edj1YdA08Gwq:b-896fix) ([raw file](https://github.com/vaadin/spreadsheet/blob/fb52db7de7e44637160677cb55688a0b0b968c25/vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/demoapps/FileDataSource.java#L37)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary>
> handle in a nicer way
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/414)*

**Comment by alvarezguille** [comment]
Reviewed 10 of 83 files at r2.
Review status: 10 of 16 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/414)*

**Comment by alvarezguille** [comment]
some references still have the headers

---

Review status: 10 of 16 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/414#-:-KX6GlLUTzKiCXirYN4D:b-9vlpdk)*

**Comment by rogozinds** [comment]
Reviewed 3 of 83 files at r2, 2 of 69 files at r3.
Review status: 12 of 16 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/414)*

**Comment by rogozinds** [comment]
Reviewed 1 of 2 files at r1.
Review status: 12 of 16 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/demoapps/FileDataSource.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/414#-KWrvftxUT-frIgo8VuF:-KXA0hZxOiDj-H9kWeIf:b-896fix) ([raw file](https://github.com/vaadin/spreadsheet/blob/fb52db7de7e44637160677cb55688a0b0b968c25/vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/demoapps/FileDataSource.java#L37)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary>
> Done.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/414)*

**Comment by alvarezguille** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/414)*

**Pull request merged**
