### PR TITLE
Header transparency on screenshots

### PR DESCRIPTION
**Pull request by MTzukanov**
Automatically add transparency to the header area of error screenshots.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/498)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/spreadsheet/498#-KfMYEuc1SYLVh_2Md04:-KfMYEuc1SYLVh_2Md05:b-qdo7dd) (no related file):*
Did you know that you can use `TestBenchElement.compareScreen` to just compare an element and not the whole view? Sounds a bit like this is what you need

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/498)*

**Comment by MTzukanov** [comment]
Yes, I know. Two problems:
1) if we change to it, we need to update all the tests and screenshots (many!).
2) Compare element is available only in TB 4.2, Spreadsheet uses an older version. Not sure if upgrade is possible/straightforward.

**Comment by MTzukanov** [comment]
Another concern with element screenshot is the following: sometimes there are popups over the spreadsheet, can element compare see them?

**Comment by rogozinds** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/498#-:-KfpEZNGBoRjp_rIMDwn:bnfp4nl)*

**Pull request merged**
