### PR TITLE
Disable overflow and break long words if cell is set to wrap

### PR DESCRIPTION
**Pull request by tepi**
Tagetik 37

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/514)

### CODE REVIEW

**Comment by rogozinds** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/WrappedTextNotOverflowingTest.java, line 21 at r3](https://reviewable.io:443/reviews/vaadin/spreadsheet/514#-KhbSAUCgvfOkB1SAJx4:-KhbSAUDx7TZ36FPg2o7:b-o3whyb) ([raw file](https://github.com/vaadin/spreadsheet/blob/0a0cc04c687724eccb4b52c09597265a2f1625e2/vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/WrappedTextNotOverflowingTest.java#L21)):*
> @RunLocally(Browser.PHANTOMJS)
This should be removed

---

*[vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/WrappedTextNotOverflowingTest.java, line 66 at r3](https://reviewable.io:443/reviews/vaadin/spreadsheet/514#-KhbVJffhOcVvJAM_rQl:-KhbVJfgzlE8ws96_Dzv:be5nast) ([raw file](https://github.com/vaadin/spreadsheet/blob/0a0cc04c687724eccb4b52c09597265a2f1625e2/vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/WrappedTextNotOverflowingTest.java#L66)):*
>  // For some reason it works fine even if bug is not fixed
So does this comment mean, is it working, though it should not?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/514)*

**Comment by rogozinds** [comment]
For some reason the text goes down. And rendered partly in the lower cells.
I'm talking about C3, C4, C5 cells. That should be fixed.

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/514#-:-KhzpWUF7O3IX6idSGoJ:b-cml4lt)*

**Comment by rogozinds** [comment]
Reviewed 1 of 7 files at r2, 1 of 7 files at r3.
Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/514)*

**Comment by rogozinds** [comment]
I would also add screenshot test here, as in the DOM everything is "ok", but the end result is unexpected.

---

Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/514#-:-Khzt1x1JZxurqPADjYD:bbitz3n)*

**Comment by MTzukanov** [comment]
Close this, https://github.com/vaadin/spreadsheet/pull/514 fixes it in a much more better way.

**Pull request closed without merging**
