### PR TITLE
Update to vaadin 8.0.0.alpha6.

### PR DESCRIPTION
**Pull request by rogozinds**
Fix pom, fix demoUI, fix widgetset, use compatibility-package

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/403)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 22 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/spreadsheet/403#-KW3Bzfa0RH-9v-Lge4Y:-KW3Bzfa0RH-9v-Lge4Z:b-nje9j) (no related file):*
Update tests so they are not run on IE10

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/403)*

**Comment by alvarezguille** [comment]
Reviewed 3 of 22 files at r1.
Review status: 3 of 22 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[vaadin-spreadsheet/pom.xml, line 24 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/403#-KW3ALpzHgz9P7iYhnkq:-KW3ALpzHgz9P7iYhnkr:b6mlur3) ([raw file](https://github.com/vaadin/spreadsheet/blob/1edd7d440459775bf0f55be6ea9ed6a976131e22/vaadin-spreadsheet/pom.xml#L24)):*
> <testbench.api.version>7.5.7</testbench.api.version>
doesn't change much but shouldn't be downgraded

---

*[vaadin-spreadsheet/pom.xml, line 280 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/403#-KW3BK3s8zbKzVjzn9v6:-KW3BK3s8zbKzVjzn9v7:bxpf1d3) ([raw file](https://github.com/vaadin/spreadsheet/blob/1edd7d440459775bf0f55be6ea9ed6a976131e22/vaadin-spreadsheet/pom.xml#L280)):*
> ```XML
>                 <configuration>
>                     <httpConnector>
>                         
> ```

remove commented

---

*[vaadin-spreadsheet/pom.xml, line 288 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/403#-KW3BMX0oaFw_AvlyFAF:-KW3BMX0oaFw_AvlyFAG:b-jus1gz) ([raw file](https://github.com/vaadin/spreadsheet/blob/1edd7d440459775bf0f55be6ea9ed6a976131e22/vaadin-spreadsheet/pom.xml#L288)):*
> connectors>-->
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>                         
>                             
>                             
>                         
>

**Comment by alvarezguille** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/spreadsheet/403#-KW3Bzfa0RH-9v-Lge4Y:-KW3FPk9zlRm5pgtCN8d:b-vjsjbw) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> Update tests so they are not run on IE10
</details>
and remove unused references

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/403)*

**Comment by rogozinds** [comment]
Review status: 3 of 28 files reviewed at latest revision, 10 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/spreadsheet/403#-KW3Bzfa0RH-9v-Lge4Y:-KWc0uV_WOH966_EH1of:bww787d) (no related file):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary>
> and remove unused references
</details>
Exclude IE 10 will remove unused references in the next patch

---

*[vaadin-spreadsheet/pom.xml, line 24 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/403#-KW3ALpzHgz9P7iYhnkq:-KW3QllVLe_5yKs8eYgV:b-896fix) ([raw file](https://github.com/vaadin/spreadsheet/blob/1edd7d440459775bf0f55be6ea9ed6a976131e22/vaadin-spreadsheet/pom.xml#L24)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary>
> > <testbench.api.version>7.5.7</testbench.api.version>
> doesn't change much but shouldn't be downgraded
</details>
Done.

---

*[vaadin-spreadsheet/pom.xml, line 280 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/403#-KW3BK3s8zbKzVjzn9v6:-KW3QvL2T9KLUPRZt37S:b-896fix) ([raw file](https://github.com/vaadin/spreadsheet/blob/1edd7d440459775bf0f55be6ea9ed6a976131e22/vaadin-spreadsheet/pom.xml#L280)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary>
> remove commented
</details>
Done.

---

*[vaadin-spreadsheet/pom.xml, line 288 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/403#-KW3BMX0oaFw_AvlyFAF:-KW3QyNUkcm8Z6Wa8KWx:b-896fix) ([raw file](https://github.com/vaadin/spreadsheet/blob/1edd7d440459775bf0f55be6ea9ed6a976131e22/vaadin-spreadsheet/pom.xml#L288)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary>
> > connectors>-->
> >                         
> >                             
> >                             
> >                         
> >

**Comment by alvarezguille** [comment]
Reviewed 14 of 23 files at r1, 14 of 14 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/403)*

**Pull request merged**
