### PR TITLE
Named range reference feature

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/561)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Check #552 for comments.

**Comment by alvarezguille** [comment]
Reviewed 5 of 22 files at r1, 1 of 1 files at r3.
Review status: 6 of 26 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/CellSelectionShifter.java, line 419 at r4](https://reviewable.io:443/reviews/vaadin/spreadsheet/561#-Kp-tjhTU9XAiayTeNdf:-Kp-tjhTU9XAiayTeNdg:b-k1xzbv) ([raw file](https://github.com/vaadin/spreadsheet/blob/c729e74cb26c45de931f3569c44cf6e795b9fb51/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/CellSelectionShifter.java#L419)):*
>   getCellSelectionManager().handleCellRangeSelection(null,
>                             selectedCellReference, newPaintedCellRange, false);

should the overload without null param be used?

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetHistoryManager.java, line 233 at r4](https://reviewable.io:443/reviews/vaadin/spreadsheet/561#-Kp-twCOZX-rnM0SYO_I:-Kp-twCOZX-rnM0SYO_J:bd56jci) ([raw file](https://github.com/vaadin/spreadsheet/blob/c729e74cb26c45de931f3569c44cf6e795b9fb51/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetHistoryManager.java#L233)):*
>                             .handleCellRangeSelection(null, selectedCellReference,
>                                     paintedCellRange, true);

Should the overload without null param be used?

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java, line 4845 at r4](https://reviewable.io:443/reviews/vaadin/spreadsheet/561#-Kp-r_r6c6XJMvkLHLLj:-Kp-r_r6c6XJMvkLHLLk:b5fy3bd) ([raw file](https://github.com/vaadin/spreadsheet/blob/c729e74cb26c45de931f3569c44cf6e795b9fb51/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java#L4845)):*
>         if (rows.size() == 0)
>             return lastColumnIndex;

Use curly braces

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetClientRpc.java, line 40 at r4](https://reviewable.io:443/reviews/vaadin/spreadsheet/561#-Kp-sjBVm1h4leJq4FqC:-Kp-sjBVm1h4leJq4FqD:beyfb3j) ([raw file](https://github.com/vaadin/spreadsheet/blob/c729e74cb26c45de931f3569c44cf6e795b9fb51/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetClientRpc.java#L40)):*
> void showCellValue(String possibleName, int col, int row);

this signature makes little since now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/561)*

**Comment by MTzukanov** [comment]
Review status: 6 of 26 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/CellSelectionShifter.java, line 419 at r4](https://reviewable.io:443/reviews/vaadin/spreadsheet/561#-Kp-tjhTU9XAiayTeNdf:-KpEB_JZ7TxTQFFk5XN6:bk8zqp5) ([raw file](https://github.com/vaadin/spreadsheet/blob/c729e74cb26c45de931f3569c44cf6e795b9fb51/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/CellSelectionShifter.java#L419)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>   getCellSelectionManager().handleCellRangeSelection(null,
>                             selectedCellReference, newPaintedCellRange, false);

should the overload without null param be used?
</blockquote></details>

Fixed. Added another overload method

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetHistoryManager.java, line 233 at r4](https://reviewable.io:443/reviews/vaadin/spreadsheet/561#-Kp-twCOZX-rnM0SYO_I:-KpEBdaqDSG8HfROrOdh:b-886gsx) ([raw file](https://github.com/vaadin/spreadsheet/blob/c729e74cb26c45de931f3569c44cf6e795b9fb51/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetHistoryManager.java#L233)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>                             .handleCellRangeSelection(null, selectedCellReference,
>                                     paintedCellRange, true);

Should the overload without null param be used?
</blockquote></details>

Fixed

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java, line 4845 at r4](https://reviewable.io:443/reviews/vaadin/spreadsheet/561#-Kp-r_r6c6XJMvkLHLLj:-KpE9c2831GEkjsXbsDy:bt2vr0b) ([raw file](https://github.com/vaadin/spreadsheet/blob/c729e74cb26c45de931f3569c44cf6e795b9fb51/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java#L4845)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>         if (rows.size() == 0)
>             return lastColumnIndex;

Use curly braces
</blockquote></details>

Fixed

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetClientRpc.java, line 40 at r4](https://reviewable.io:443/reviews/vaadin/spreadsheet/561#-Kp-sjBVm1h4leJq4FqC:-KpE9-UsJmEgOqibSvDz:b-68wi0h) ([raw file](https://github.com/vaadin/spreadsheet/blob/c729e74cb26c45de931f3569c44cf6e795b9fb51/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetClientRpc.java#L40)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> void showCellValue(String possibleName, int col, int row);

this signature makes little since now
</blockquote></details>

Renamed the method

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/561)*

**Comment by rogozinds** [comment]
Reviewed 13 of 22 files at r1, 1 of 3 files at r2, 1 of 1 files at r3, 4 of 9 files at r4, 7 of 7 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/561)*

**Comment by rogozinds** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/561)*

**Pull request merged**
