### PR TITLE
Update to POI 3.17 release

### PR DESCRIPTION
**Pull request by tuliogarcia**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/617)

### CODE REVIEW

**Comment by WoozyG** [comment]
I waited too long, and can no longer see which tests are failing in TeamCity.  Can someone send me the last build log or run another one?  I'm finally freeing some cycles from our product release to work on this.  

I have more contributions, including Excel theme and table style support, but they need this integrated first.  Also, the failures are unexpected, and I'm concerned a bug may have crept into POI 3.17 between the last beta and release.

**Comment by alvarezguille** [comment]
Hi @WoozyG, it looks like the original build was archived, I've restarted it and now the log should be available again in [teamcity](http://teamcity.vaadin.com/viewLog.html?buildId=29852&buildTypeId=VaadinSpreadsheet_SpreadsheetsPreCommitBuildMasterPhantomHub&guest=1)

**Comment by WoozyG** [comment]
These three failures appear to be due to some bugs in my POI conditional formatting evaluation.  Thanks for the unit tests, I've used them to find and fix the issues.  Unfortunately the fix is in POI trunk, with the next release being 4.0 with all the deprecated code removed.  I was out of the country for some of the early discussions on other changes, but I think it is mostly new things and clean-up.  Haven't checked to see if Vaadin Spreadsheet still compiles with a current snapshot build.

POI bugs I found and fixed for these tests:

[61764](https://bz.apache.org/bugzilla/show_bug.cgi?id=61764) Conditional formatting rules don't evaluate properly for some multi-range rule definitions

[61761](https://bz.apache.org/bugzilla/show_bug.cgi?id=61761) Conditional formatting rule evaluation doesn't like comparing cells of different types

Both are deep enough I couldn't find a workaround usable on the Vaadin side as a temporary fix.

I'll leave it to you folks what you want to do about these.  They could be commented out and the bugs lived with for now, or the plan could change to waiting for 4.0, or something else I can't think of this late.

**Comment by alexberazouski** [comment]
Reviewed 4 of 5 files at r1, 3 of 3 files at r2, 4 of 4 files at r3, 1 of 1 files at r4, 5 of 5 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/617)*

**Pull request merged**
