### PR TITLE
Fix Unable to configure jsr356 exception in jetty

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/409)

### CODE REVIEW

**Comment by Artur-** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-spreadsheet-charts/src/main/resources/com/vaadin/addon/spreadsheet/charts/WidgetSet.gwt.xml, line 29 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/409#-KWlY7rS6sLf9KNkdUmG:-KWlY7rS6sLf9KNkdUmH:b7cxj1x) ([raw file](https://github.com/vaadin/spreadsheet/blob/93f21ab39f7af2828ba7b85f7e48a9d977731467/vaadin-spreadsheet-charts/src/main/resources/com/vaadin/addon/spreadsheet/charts/WidgetSet.gwt.xml#L29)):*
> ```XML
>     <inherits name="com.vaadin.DefaultWidgetSet" />
> 
>     <inherits name="com.vaadin.v7.Vaadin7WidgetSet" />
> ```

How is this related?

---

*[vaadin-spreadsheet-charts/src/test/resources/jetty-context.xml, line 7 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/409#-KWlY3F1qHA83I0X3zFg:-KWlY3F1qHA83I0X3zFh:bng1oir) ([raw file](https://github.com/vaadin/spreadsheet/blob/93f21ab39f7af2828ba7b85f7e48a9d977731467/vaadin-spreadsheet-charts/src/test/resources/jetty-context.xml#L7)):*
> ```XML
>     <Call name="setAttribute">
>         <Arg>org.eclipse.jetty.server.webapp.WebInfIncludeJarPattern</Arg>
>         <Arg>.*</Arg>
> ```

Why is this done in a different way than vaadin-spreadsheet/pom.xml?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/409)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 4 files at r1, 15 of 16 files at r2.
Review status: 16 of 17 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/409)*

**Comment by Artur-** [comment]
Reviewed 1 of 16 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/409)*

**Comment by rogozinds** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-spreadsheet-charts/src/test/resources/jetty-context.xml, line 7 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/409#-KWlY3F1qHA83I0X3zFg:-KWqh0zHGzj1-resY8rr:baobx8i) ([raw file](https://github.com/vaadin/spreadsheet/blob/93f21ab39f7af2828ba7b85f7e48a9d977731467/vaadin-spreadsheet-charts/src/test/resources/jetty-context.xml#L7)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> Why is this done in a different way than vaadin-spreadsheet/pom.xml?
</details>
Now it's done the same way

---

*[vaadin-spreadsheet-charts/src/main/resources/com/vaadin/addon/spreadsheet/charts/WidgetSet.gwt.xml, line 29 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/409#-KWlY7rS6sLf9KNkdUmG:-KWqh5bbHd0_WVJ9eWph:b-hfpv0l) ([raw file](https://github.com/vaadin/spreadsheet/blob/93f21ab39f7af2828ba7b85f7e48a9d977731467/vaadin-spreadsheet-charts/src/main/resources/com/vaadin/addon/spreadsheet/charts/WidgetSet.gwt.xml#L29)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> How is this related?
</details>
removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/409)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 4 files at r1, 1 of 16 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/409)*

**Pull request merged**
