### PR TITLE
Allows arrow keys to leave cell value editor

### PR DESCRIPTION
**Pull request by gatanaso**
Selecting a cell via single-clicking or via arrow keys, entering a value by typing, and then using the arrow keys again saves the new value and moves to the appropriate adjacent cell.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/601)

### CODE REVIEW

**Comment by vlukashov** [comment]
This PR breaks the functionality of selecting arguments with arrow keys when editing formulas:

Before (current master):


After (with this PR):


---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/FormulaBarWidget.java, line 92 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/601#-KsmuA-hy7xPkkqqUWco:-KsmuA-ir5oObeB5i2VZ:bbh93r2) ([raw file](https://github.com/vaadin/spreadsheet/blob/0518804beb15501b9004731b17f6ff43167329a5/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/FormulaBarWidget.java#L92)):*
> ```Java
>     private boolean enableKeyboardNavigation;
>     private TextBox currentEditor;
>     private boolean doubleClickOrEditMode;
> ```

Is there any particular reason why the `doubleClickOrEditMode` flag is in a different class than the `inputFullFocus` flag? If they are close in usage and purpose, I suggest to place them together.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetInputEventListener.java, line 51 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/601#-KsmsjetSuQHRk4pTIeW:-KsmsjetSuQHRk4pTIeX:b-qjkr4t) ([raw file](https://github.com/vaadin/spreadsheet/blob/0518804beb15501b9004731b17f6ff43167329a5/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetInputEventListener.java#L51)):*
Does this comment accurately describe how the `inputFullFocus` flag is actually used?

It looks like there are 3 possible states:
 - no focus
 - light focus (arrow keys select an adjacent cell)
 - full focus (arrow keys move the cursor inside the current cell)

And from these 3 options the `inputFullFocus` corresponds to the second one (light focus):
> if (!inputFullFocus || (inputFullFocus && !formulaBarWidget.isDoubleClickOrEditMode())) {

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/601#-:-Ksmvw2OtnIVTEUK7wWb:ba76h10)*

**Comment by gatanaso** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/FormulaBarWidget.java, line 92 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/601#-KsmuA-hy7xPkkqqUWco:-KsrHnxhg_Vq00VPqBYW:bsjscuc) ([raw file](https://github.com/vaadin/spreadsheet/blob/0518804beb15501b9004731b17f6ff43167329a5/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/FormulaBarWidget.java#L92)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Is there any particular reason why the `doubleClickOrEditMode` flag is in a different class than the `inputFullFocus` flag? If they are close in usage and purpose, I suggest to place them together.
</blockquote></details>

Placing the 'doubleClickOrEditMode' flag in the FormulaBarWidget is purely because that flag is related to the state of the widget itself.
However I do agree that they are close in usage and purpose with the 'inputFullFocus' flag. It would make sense to place them together, although I believe that should be done as part of a task to possibly merge all or some parts of the FormulaBarWidget with the SheetInputEventListener.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetInputEventListener.java, line 51 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/601#-KsmsjetSuQHRk4pTIeW:-KsrC2UEV0Ome5wHXQZt:bwlr87v) ([raw file](https://github.com/vaadin/spreadsheet/blob/0518804beb15501b9004731b17f6ff43167329a5/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetInputEventListener.java#L51)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Does this comment accurately describe how the `inputFullFocus` flag is actually used?

It looks like there are 3 possible states:
 - no focus
 - light focus (arrow keys select an adjacent cell)
 - full focus (arrow keys move the cursor inside the current cell)

And from these 3 options the `inputFullFocus` corresponds to the second one (light focus):
> if (!inputFullFocus || (inputFullFocus && !formulaBarWidget.isDoubleClickOrEditMode())) {

</blockquote></details>

I interpret the comment as follows:

* The cell has 'full focus' when it's double-clicked or in edit mode (achieved by pressing F2 or the 'enter' key) -  meaning that the arrow keys change the input caret position, which aligns with your definition of 'full focus'.

* Also it states that otherwise it's not in 'full focus' - meaning that the arrow keys select an adjacent cell, which aligns with your definition of 'light focus'.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/601)*

**Comment by gatanaso** [comment]
I pushed an update to the PR that allows this functionality. Thank you! :)

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/601#-:-KsrQtMhddsaAhTb0WxZ:btfqrba)*

**Comment by vlukashov** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/601#-:-KswSVSXGAtYGg7PhML9:bnfp4nl)*

**Pull request merged**
