### PR TITLE
Correctly handle hyperlinks with cell ref as first argument

### PR DESCRIPTION
**Pull request by tepi**
Tagetik 43.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/513)

### CODE REVIEW

**Comment by rogozinds** [comment]
Change ConditionalFormatter.getValueEvalFromFormula to use WorkbookEvaluatorUtil.evaluate
So:
private ValueEval getValueEvalFromFormula(String formula, Cell cell, int deltaColumn, int deltaRow) {
  returrn WorkbookEvaluatorUtil.evaluate(spreadsheet, cell, formula, deltaRow, deltaColumn.)
}

---

Reviewed 2 of 5 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/513#-:-KhaU86oOilNmzgbqKrH:b-7zssu2)*

**Comment by rogozinds** [comment]
Needs rebase

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/513#-:-KhaVX34JOhPeYQrGv94:b-apz0tw)*

**Comment by kiaruska** [comment]
Rebase done

**Comment by MTzukanov** [comment]
https://github.com/tagetik/tagetik-2017-spreadsheet/issues/43

**Comment by alvarezguille** [comment]
Reviewed 1 of 3 files at r4, 2 of 4 files at r5, 1 of 4 files at r6.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/DefaultHyperlinkCellClickHandler.java, line 138 at r6](https://reviewable.io:443/reviews/vaadin/spreadsheet/513#-Ki_IuOgBcZDXnf5Pa_L:-Ki_IuOgBcZDXnf5Pa_M:br4xqck) ([raw file](https://github.com/vaadin/spreadsheet/blob/0af9db941e181536d65d3e7f8aa8161e6c1f7822/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/DefaultHyperlinkCellClickHandler.java#L138)):*
>             if (firstArgCell != null)
>                 address = spreadsheet.getCellValue(firstArgCell);

please add braces and remove trailing spaces

```
            if (firstArgCell != null) {
                address = spreadsheet.getCellValue(firstArgCell);
            }
```

I tried doing it myself but don't have push access

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/513)*

**Comment by MTzukanov** [comment]
@alvarezguille Fixed!

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/513)*

**Pull request merged**
