### PR TITLE
Handle NotImplementedExpection for subtotal formulas (SHEET-307)

### PR DESCRIPTION
**Pull request by alvarezguille**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/404)

### CODE REVIEW

**Comment by rogozinds** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/ConditionalFormattingTest.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/404#-KW6zAc5OrsasnqdI9CT:-KW6zAc6v3LrzPfojM3k:bhxpwb4) ([raw file](https://github.com/vaadin/spreadsheet/blob/e0adb2faee3c798f74028f059c855db68f68afe3/vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/ConditionalFormattingTest.java#L36)):*
> @Override
>     public List<DesiredCapabilities> getBrowsersToTest() {
>         return getBrowserCapabilities(Browser.PHANTOMJS);
>     }
Remove it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/404)*

**Comment by rogozinds** [comment]
Reviewed 1 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/404)*

**Comment by rogozinds** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/404#-:-KW71Y7uM4yZEvPCCnTt:bnfp4nl)*

**Comment by alvarezguille** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/ConditionalFormattingTest.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/404#-KW6zAc5OrsasnqdI9CT:-KW71mN4k2uOPbQFm3l8:b-896fix) ([raw file](https://github.com/vaadin/spreadsheet/blob/e0adb2faee3c798f74028f059c855db68f68afe3/vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/ConditionalFormattingTest.java#L36)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary>
> > @Override
> >     public List<DesiredCapabilities> getBrowsersToTest() {
> >         return getBrowserCapabilities(Browser.PHANTOMJS);
> >     }
> Remove it
> 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/404)*

**Pull request merged**
