### PR TITLE
Fixes exception when clicking on chart which has filtered-out columns in its data

### PR DESCRIPTION
**Pull request by tepi**
Tagetik issue 41

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/508)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Reviewed 1 of 3 files at r2, 1 of 2 files at r3.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/Spreadsheet.java, line 4549 at r3](https://reviewable.io:443/reviews/vaadin/spreadsheet/508#-Kgy3_Zas88Ch-CotEyH:-Kgy3_Zas88Ch-CotEyI:b-ve2xk8) ([raw file](https://github.com/vaadin/spreadsheet/blob/36a31756440e8eb098638780f0cc724cd630034b/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/Spreadsheet.java#L4549)):*
> ```Java
>      *
>      */
>     public void setSelection(String selectionRange) {
> ```

Current implementation is not really doing what the new javadoc says regarding contiguous area containing them.
For instance `spreadsheet.setSelection("(B3:C5,B2:E4)");  ` results in a selection (B3:E4) that doesn't  contain any of the regions. 
Using AreaReference seems to be very helpful (nice discovery by the way),  but I would suggest moving this logic to the spreadsheet-charts section that calls setSelection, and leave setSelection as it was.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/508)*

**Comment by alvarezguille** [comment]
*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/Spreadsheet.java, line 4549 at r3](https://reviewable.io:443/reviews/vaadin/spreadsheet/508#-Kgy3_Zas88Ch-CotEyH:-Kgy7AZVOTzZldatcXRK:b-35rvy7) ([raw file](https://github.com/vaadin/spreadsheet/blob/36a31756440e8eb098638780f0cc724cd630034b/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/Spreadsheet.java#L4549)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

Current implementation is not really doing what the new javadoc says regarding contiguous area containing them.
For instance `spreadsheet.setSelection("(B3:C5,B2:E4)");  ` results in a selection (B3:E4) that doesn't  contain any of the regions. 
Using AreaReference seems to be very helpful (nice discovery by the way),  but I would suggest moving this logic to the spreadsheet-charts section that calls setSelection, and leave setSelection as it was.
</blockquote></details>

When moved to vaadin-spreadsheet-charts, looks like some code could be shared with com.vaadin.addon.spreadsheet.charts.converter.Utils.getAllReferencedCells

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/508)*

**Comment by MTzukanov** [comment]
https://github.com/tagetik/tagetik-2017-spreadsheet/issues/41

**Comment by MTzukanov** [comment]
This one is ready for review

**Comment by alvarezguille** [comment]
Reviewed 4 of 4 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/508)*

**Pull request merged**
