### PR TITLE
Prevent client-side exception if mouse up is done outside of browser window

### LINKED ISSUE #437: Column/Row resize gets stuck if mouse up is done outside window browser
Its can be tested in [Demo](demo.vaadin.com/spreadsheet).
Implementation is done in NativePreviewHandler in SheetWidget.
PreviewHandler is registered the whole time, no only while resizing.
This is also related to #436 because onPreviewNativeEvent when the handle in the split panel is moved. Fix should also be tested with spreadsheet-demo without locked HorizontalSplitPanel

### PR DESCRIPTION
**Pull request by alvarezguille**
Prevent error in NativePreviewHandler making row/column resize get stuck

Fixes #437

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/590)

### CODE REVIEW

**Comment by alvarezguille** [comment]
No trivial way of adding an TB test for this

**Comment by Artur-** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java, line 1512 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/590#-Kq3gc352nwlqAeowQUT:-Kq3gc352nwlqAeowQUU:bi4r8f8) ([raw file](https://github.com/vaadin/spreadsheet/blob/eb362e19d80739645dc5e5569c3529b388c776c3/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java#L1512)):*
> ```Java
>                             className = target.getAttribute("class");
>                         } catch (JavaScriptException e) {
>                             // for some reason if target is the HTML element
> ```

What does this comment mean? If the target is what HTML element? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/590)*

**Comment by alvarezguille** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java, line 1512 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/590#-Kq3gc352nwlqAeowQUT:-Kq6ofRvy1WZxRwDl4bE:bom5mwe) ([raw file](https://github.com/vaadin/spreadsheet/blob/eb362e19d80739645dc5e5569c3529b388c776c3/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java#L1512)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

What does this comment mean? If the target is what HTML element? 
</blockquote></details>

the root HTML element
the exception is "elem.getAttribute is not a function"
although now I'm testing and element has no tagname nor inner text
any clue? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/590)*

**Comment by alexberazouski** [comment]
Tested manually; 
cannot reproduce any exceptions; 
cells resize is working as expected;

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/590#-:-Kq74cCr2MrXQen7yu-b:b-xa2lz2)*

**Comment by alvarezguille** [comment]
*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java, line 1512 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/590#-Kq3gc352nwlqAeowQUT:-Kq7Kq8MXH30-TSD0Sqn:bv0yotp) ([raw file](https://github.com/vaadin/spreadsheet/blob/eb362e19d80739645dc5e5569c3529b388c776c3/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java#L1512)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

the root HTML element
the exception is "elem.getAttribute is not a function"
although now I'm testing and element has no tagname nor inner text
any clue? 
</blockquote></details>

After further investigation I noticed that the event target is HTMLDocument, that explains `getAttribute is not a function`. Updated the comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/590)*

**Comment by Artur-** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/590)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/590)*

**Pull request merged**
