### PR TITLE
Support for Excel leading quote style option

### PR DESCRIPTION
**Pull request by MTzukanov**
Spreadsheet does not use the leading quote style option correctly, this patch fixes it.

https://github.com/tagetik/tagetik-2017-spreadsheet/issues/47

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/525)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Test failures seem to be related to the changes in `SpreadsheetDemoUI`, the test UI fails. Also branch needs rebasing.

**Comment by alvarezguille** [comment]
Found a small issue that seems to be related to the change ( as I can reproduce it with 1.3 head), to reproduce: 

1. Create new spreadsheet
2. Set A1 value to `'1`
3. Select A1
4. A1 shows `1` and formula bar shows `'1` as expected
5. Create a new sheet
6. Go back to sheet 1
7. Now A1 shows `1` and formula bar shows `1` without the leading quote

**Comment by alvarezguille** [comment]
Also pasting content with leading quote like `'138` results in double quotes

**Comment by alvarezguille** [comment]
Reviewed 2 of 4 files at r7.
Review status: 2 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/525)*

**Comment by alessandroguarascio** [comment]
> Also pasting content with leading quote like '138 results in double quotes
I noticed that Excel has a "strange" (I would say "buggy") behaviour, and I don't know if the best way is to replicate exactly it or to keep a more "plain" approach:

In fact, in Excel, if you paste '1234, Excel doesn't add an additional quote in editor: this means that entering the cell and just clicking <enter>, the leading quote is removed, and the cell content is changed. It's not clear what the use case should be. Options are: 

1. **The user wants to add 1234 as text (without seeing the quote)** so the initial Excel (and Spreadsheet) behaviour is not correct because it initially shows the quote, 
2. **The user wants to add exactly the string '1234** : so the Excel behaviour is wrong because just entering the cell removes the quote and the Spreadsheet correctly adds an additional quote (to escape the "original" one) in editor.

What do you think? Should we replicate such a "strange" Excel behaviour?

**Comment by alvarezguille** [comment]
About the pasting I think the best behavior would be to treat it as is you paste in the inline editor or just type it.
But current behavior seems to be like excel so it's not wrong.

I made a small comment about null safety, with that and the references update for the failing test I think this is ok to merge.

---

Reviewed 2 of 5 files at r3, 2 of 2 files at r9, 4 of 5 files at r10.
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetUtil.java, line 440 at r10](https://reviewable.io:443/reviews/vaadin/spreadsheet/525#-KjvKPH8yNZ55P_ecYRi:-KjvKPH8yNZ55P_ecYRj:bo9zr8h) ([raw file](https://github.com/vaadin/spreadsheet/blob/619ec32186d36e1a7e8be2df0eac7f86e7098d79/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/SpreadsheetUtil.java#L440)):*
> cellStyle.getCoreXf()

I'm not sure if `getCoreXf()` can return null but I would check, it's coming from model, and it's quite easy to make it nullsafe

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/FormulaBarWidget.java, line 954 at r10](https://reviewable.io:443/reviews/vaadin/spreadsheet/525#-KjvQ2TcOCaljGtT9Zeu:-KjvQ2TcOCaljGtT9Zev:b2cx7yk) ([raw file](https://github.com/vaadin/spreadsheet/blob/00d6d6ee9a4770faa39bddff313126000fa11e24/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/FormulaBarWidget.java#L954)):*
> setCellPlainValue

was there a reason to leave `setCellPlainValue` and remove `setFormulaFieldValue` and not otherwise? (Just asking, doesn't need to be changed)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/525#-:-KjvbIt-TjPPVx_eXad8:b3g2b04)*

**Comment by MTzukanov** [comment]
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/FormulaBarWidget.java, line 954 at r10](https://reviewable.io:443/reviews/vaadin/spreadsheet/525#-KjvQ2TcOCaljGtT9Zeu:-KjwJVChF3gj4Jkq2m0Q:bn4h6b8) ([raw file](https://github.com/vaadin/spreadsheet/blob/00d6d6ee9a4770faa39bddff313126000fa11e24/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/FormulaBarWidget.java#L954)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> setCellPlainValue

was there a reason to leave `setCellPlainValue` and remove `setFormulaFieldValue` and not otherwise? (Just asking, doesn't need to be changed)
</blockquote></details>

No specific reason :) Neither I can see a specific reason to do otherwise, totally equivalent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/525)*

**Comment by alvarezguille** [comment]
*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/FormulaBarWidget.java, line 954 at r10](https://reviewable.io:443/reviews/vaadin/spreadsheet/525#-KjvQ2TcOCaljGtT9Zeu:-KjwSFqBpN1YXABACBjl:b-4wmlur) ([raw file](https://github.com/vaadin/spreadsheet/blob/00d6d6ee9a4770faa39bddff313126000fa11e24/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/FormulaBarWidget.java#L954)):*
<details><summary><i>Previously, MTzukanov wrote…</i></summary><blockquote>

No specific reason :) Neither I can see a specific reason to do otherwise, totally equivalent.
</blockquote></details>

`setFormulaFieldValue` was more explicit of what it does, but implementation is the same and I think `setCellPlainValue` was called more times for some reason. I guess at some point they were different

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/525)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/525)*

**Comment by MTzukanov** [comment]
This is ready for review and merge.

**Comment by alvarezguille** [comment]
Reviewed 5 of 5 files at r12, 2 of 2 files at r13.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/525)*

**Pull request merged**
