### PR TITLE
Conditional Formatting - blank cell support

### PR DESCRIPTION
**Pull request by MTzukanov**
In some cases blank cells are not handled correctly, this patch fixes it.

https://github.com/tagetik/tagetik-2017-spreadsheet/issues/42

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/544)

### CODE REVIEW

**Comment by alvarezguille** [comment]
*[vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/ConditionalFormattingCellValueIsTest.java, line 126 at r4](https://reviewable.io:443/reviews/vaadin/spreadsheet/544#-KmevG7R1ObK5sdbPlCc:-KmevG7R1ObK5sdbPlCd:b-28wsrq) ([raw file](https://github.com/vaadin/spreadsheet/blob/a4bbec04d2b8575df813ab6a2038aa4fdf1d3648/vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/ConditionalFormattingCellValueIsTest.java#L126)):*
> //        spreadsheetPage.deleteCellValue("B2");
> //        spreadsheetPage.deleteCellValue("B3");
> //        assertEquals(TRUE_CONDITION_COLOR, spreadsheetPage.getCellColor("B3"));

should commented code be deleted or uncommented? would it fail? should it fail?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/544)*

**Comment by kiaruska** [comment]
> //        spreadsheetPage.deleteCellValue("B2");
> //        spreadsheetPage.deleteCellValue("B3");
> //        assertEquals(TRUE_CONDITION_COLOR, spreadsheetPage.getCellColor("B3"));

This code was committed by Michael
with message "Commented out deleted related tests as it doesn't work right now"
Sorry, I haven't more infomation

I'm available for further investigation.

**Comment by MTzukanov** [comment]
I added a comment to the file and duplicating it here:
Currently deleting a cell does not affect its own color (bug), although all other cells are updated.
Commenting out cell deletion test here and in all other methods until this issue is resolved.
https://github.com/vaadin/spreadsheet/issues/577

**Comment by alvarezguille** [comment]
*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/Spreadsheet.java, line 1651 at r7](https://reviewable.io:443/reviews/vaadin/spreadsheet/544#-KpOt33vXLASlqF4oNUR:-KpOt33vXLASlqF4oNUS:bqgssnz) ([raw file](https://github.com/vaadin/spreadsheet/blob/a5ba62060ad46595f74c8eacee487a7216415ecb/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/Spreadsheet.java#L1651)):*
<details><summary><i alt="summary">Quoted 15 lines of code…</i></summary>
>     /**
>      * Create a new blank cell (or replace existing).
>      *
>      * After all editing is done, call {@link #refreshCells(Cell...)} or
>      * {@link #refreshAllCellValues()} to make sure the client side is updated.
>      *
>      * @param row
>      *            Row index of the new cell, 0-based
>      * @param col
>      *            Column index of the new cell, 0-based
>      * @return The newly created cell
>      * @throws IllegalArgumentException
>      *             If columnIndex < 0 or greater than the maximum number of
>      *             supported columns (255 for *.xls, 1048576 for *.xlsx)
>      */
</details>

this is invalid javadoc
run `mvn javadoc:javadoc` for error details

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/544)*

**Comment by MTzukanov** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/ConditionalFormattingCellValueIsTest.java, line 126 at r4](https://reviewable.io:443/reviews/vaadin/spreadsheet/544#-KmevG7R1ObK5sdbPlCc:-KpOtk7dZ5nQSqlVmDMK:b-rumvsc) ([raw file](https://github.com/vaadin/spreadsheet/blob/a4bbec04d2b8575df813ab6a2038aa4fdf1d3648/vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/ConditionalFormattingCellValueIsTest.java#L126)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> //        spreadsheetPage.deleteCellValue("B2");
> //        spreadsheetPage.deleteCellValue("B3");
> //        assertEquals(TRUE_CONDITION_COLOR, spreadsheetPage.getCellColor("B3"));

should commented code be deleted or uncommented? would it fail? should it fail?
</blockquote></details>

I added a comment to the file and duplicating it here:
Currently deleting a cell does not affect its own color (bug), although all other cells are updated.
Commenting out cell deletion test here and in all other methods until this issue is resolved.
#577

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/544)*

**Comment by alvarezguille** [comment]
needs manual rebase

**Comment by rolfsmeds** [comment]
Closing as inactive. Feel free to reopen if still valid.

**Pull request closed without merging**
