### PR TITLE
Fix #456, treat string valued formula cells the same as static string

### LINKED ISSUE #456: CellValueManager improperly sets cellData.needsMeasure=true for string-valued formulas
CellValueManager.createCellDataForCell(Cell)

always sets the shared state CellData field needsMeasure to true for all cells of any type other than plain String.  In Version 1.3.0 it's on line 296.

This is incorrect in the case of formula cell values that return a String.  This can be found by adding this check to the "else if" condition on line 295:

getCachedFormulaResultType()
else if (cell.getCellType() != Cell.CELL_TYPE_STRING || (cell.getCellType() == Cell.CELL_TYPE_FORMULA && cell.getCachedFormulaResultType() != Cell.CELL_TYPE_STRING) )

note the need to check first if it is a formula cell, as getCachedFormulaResultType() throws an IllegalStateException if called when the cell is not a formula.

Also, why can't I set a custom CellValueManager to fix this locally, like I can for other Spreadsheet helper classes?  That's very frustrating.

The result of this bug is that string valued formula cells are truncated in the display, while Excel displays the result text overflowing to adjoining cells if they are empty.  This is a serious display bug for our files, as there are many formula text cells with text that is expected to flow over cells to the right.

### PR DESCRIPTION
**Pull request by WoozyG**
handle the case of string valued formula cells the same as static string valued cells for the purposes of display measurement.  Fixes #456.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/495)

### CODE REVIEW

**Comment by alvarezguille** [comment]
*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/CellValueManager.java, line 297 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/495#-KgEk_PZN6ro2RZKqdYD:-KgEk_PZN6ro2RZKqdYE:b-8dxakd) ([raw file](https://github.com/vaadin/spreadsheet/blob/f0fd8172852fe7b338c3a5fde9e7fe17dc85a535/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/CellValueManager.java#L297)):*
>   

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/495)*

**Comment by alvarezguille** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/CellValueManager.java, line 297 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/495#-KgEk_PZN6ro2RZKqdYD:-KiADvGvG_wO4YzLQcum:bbcsith) ([raw file](https://github.com/vaadin/spreadsheet/blob/f0fd8172852fe7b338c3a5fde9e7fe17dc85a535/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/CellValueManager.java#L297)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>   
</blockquote></details>

this tabs should be changed for spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/495)*

**Comment by WoozyG** [comment]
edits allowed

**Comment by alvarezguille** [comment]
Current patch doesn't seems to be working for me, I tried a simple formula '=A2' where A2 had a long text and also with '=CONCATENATE(...)' formula

**Comment by WoozyG** [comment]
You are correct, I had copied my logic from my test incorrectly.  Switching || for && works for me now.

**Comment by alvarezguille** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/495)*

**Pull request merged**
