### PR TITLE
Add support for "Format only cells that contain" using a formula

### PR DESCRIPTION
**Pull request by tepi**
Add support for Excel feature "Format only cells that contain" when using a formula (Tagetik 32).

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/506)

### CODE REVIEW

**Comment by rogozinds** [comment]
Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/ConditionalFormatter.java, line 731 at r4](https://reviewable.io:443/reviews/vaadin/spreadsheet/506#-KfvoCP0WGvUVN64a6Qe:-KfvoCP1yK595QAFgRyy:b-tqbbow) ([raw file](https://github.com/vaadin/spreadsheet/blob/3420ede0e03fbf5b06f3c4d6fef086c7d31eb140/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/ConditionalFormatter.java#L731)):*
> ```Java
>      *         <code>VALUE_IS</code> rule, false otherwise
>      */
>     protected boolean matchesValue(Cell cell, ConditionalFormattingRule rule, int deltaColumn, int deltaRow) {
> ```

This is technically the API change, can we have just add an overloaded method, and the matchesValue(Cell cell, ConditionalFormattingRule fule) that calls the overloaded method with default parameters?
Or do we need to have this kind of method? Will someone call this method with deltaColumn and deltaRow different from the whole range?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/506)*

**Comment by rogozinds** [comment]
Need rebase.

**Comment by kiaruska** [comment]
Good morning, sorry for waiting my responce, but the system didn't notify me about this pull request.

The added method was necessary for the correct evaluation of shared formulas, used in conditional formatting.
Before this modify all the formulas were evaluated without considering the cell shift (column e row delta).
If it's necessary to leave the old method, I can call the newest with row and column delta equal to zero.
In this way the method (with two parameters) will have the old behaviore.

To answer the last question, the new method is called at line 646, replacing the old call.

Thanks for your help. Sorry again, for my late reply.
Chiara

**Comment by kiaruska** [comment]
When I try to rebase TAGETIK-32, I receve this message "Current branch TAGETIK-32 is up to date."
I think this happens because I have merged the 1.3 with TAGETIK-32 before.

**Comment by tepi** [comment]
*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/ConditionalFormatter.java, line 731 at r4](https://reviewable.io:443/reviews/vaadin/spreadsheet/506#-KfvoCP0WGvUVN64a6Qe:-Kgmy7udJ7QOvTDNEUDq:bv3mb51) ([raw file](https://github.com/vaadin/spreadsheet/blob/3420ede0e03fbf5b06f3c4d6fef086c7d31eb140/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/ConditionalFormatter.java#L731)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

This is technically the API change, can we have just add an overloaded method, and the matchesValue(Cell cell, ConditionalFormattingRule fule) that calls the overloaded method with default parameters?
Or do we need to have this kind of method? Will someone call this method with deltaColumn and deltaRow different from the whole range?

</blockquote></details>

After this fix, the method without the deltacol/row does not really make sense. The deltacol/row depends on where we are evaluating the formatting and there is no meaningful default parameter available. So I can't see a way to fix this issue while preserving the original API.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/506)*

**Comment by rogozinds** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/506)*

**Pull request merged**
