### PR TITLE
chore: update license headers in java files

### PR DESCRIPTION
**Pull request by manolo**
Fixes: #753

### CODE REVIEW

**Review by alvarezguille — COMMENTED** [review]
```
 * See the file license.html distributed with this software for more
 * information about licensing.
 ```
Should this go be removed? We are no longer packaging license file, this is from the time things could be downloaded from directory as a zip

**Comment by manolo** [comment]
> ```
>  * See the file license.html distributed with this software for more
>  * information about licensing.
> ```
> 
> Should this be removed? We are no longer packaging license file, this is from the time things could be downloaded from directory as a zip

@alvarezguille done

**Review by alvarezguille — CHANGES_REQUESTED** [review]
Now it's removing the `license.html` section but missing the update to `CVDLv4`

**Comment by manolo** [comment]
> Now it's removing the `license.html` section but missing the update to `CVDLv4`

Yeah, the script also changed the legacy folder. Restored that

**Comment by manolo** [comment]
Done

**Review by alvarezguille — APPROVED** [review]

**Pull request merged**
