### PR TITLE
Re-evaluate conditional formatting on cell deletion

### LINKED ISSUE #300: Delete button does not refresh conditional formatting
**Originally by _sblommers_**

---

We have 2 columns. Conditional formatting for the first columns region depends on values in the 2nd column. When we change data in the 2nd column that should change the formatting on the cell in column 1 AND we use DELETE button or TAB to jump out of the cell. In this case the conditional formatting is not reflected the way it is when pressing ENTER.

---

 Imported from https://dev.vaadin.com/ issue #18763

### PR DESCRIPTION
**Pull request by MTzukanov**
Current Spreadsheet behavior is that conditional formatting does not get evaluated when a cell value is deleted. This patch fixes it.
Fixes #300 
https://github.com/tagetik/tagetik-2017-spreadsheet/issues/30

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/503)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Found an issue that didn't happen before the changes, doesn't happen in [demo.vaadin.com/spreadsheet](public demo) with the same file at least.
Steps to reproduce: 

1. Open `conditional_formatting.xlsx` example 
2. Change A1 content to =A3 formula
3. Change A3 content to AAAAA
4. Delete A3

The stack trace is:
```
Mar 22, 2017 2:04:07 PM com.vaadin.server.DefaultErrorHandler doDefault
SEVERE: 
java.lang.IllegalStateException: Cannot get a STRING value from a NUMERIC formula cell
	at org.apache.poi.xssf.usermodel.XSSFCell.typeMismatch(XSSFCell.java:1050)
	at org.apache.poi.xssf.usermodel.XSSFCell.checkFormulaCachedValueType(XSSFCell.java:412)
	at org.apache.poi.xssf.usermodel.XSSFCell.getRichStringCellValue(XSSFCell.java:400)
	at org.apache.poi.xssf.usermodel.XSSFCell.getStringCellValue(XSSFCell.java:356)
	at com.vaadin.addon.spreadsheet.ConditionalFormatter.matchesValue(ConditionalFormatter.java:745)
	at com.vaadin.addon.spreadsheet.ConditionalFormatter.matches(ConditionalFormatter.java:639)
	at com.vaadin.addon.spreadsheet.ConditionalFormatter.runCellMatcher(ConditionalFormatter.java:547)
	at com.vaadin.addon.spreadsheet.ConditionalFormatter.createConditionalFormatterRules(ConditionalFormatter.java:251)
	at com.vaadin.addon.spreadsheet.Spreadsheet.updateMarkedCells(Spreadsheet.java:1566)
	at com.vaadin.addon.spreadsheet.CellValueManager.onDeleteSelectedCells(CellValueManager.java:841)
```

**Comment by kiaruska** [comment]
I have added a failing test about the exception. To be solved by merging this branch with [branch 32 with fix](https://github.com/tagetik/tagetik-2017-spreadsheet/issues/32)

 branch number 32 so it is necessary merge this branch later.

**Comment by tepi** [comment]
Confirmed that since tagetik32 was merged, the exception reported by Guillermo is no longer happening.

**Comment by alvarezguille** [comment]
*[vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/ConditionalFormattingOnCellDeletionTest.java, line 19 at r3](https://reviewable.io:443/reviews/vaadin/spreadsheet/503#-KhMoMBq1Rqixw2IArG8:-KhMoMBq1Rqixw2IArG9:bdit5c3) ([raw file](https://github.com/vaadin/spreadsheet/blob/66c122733252bda50e81d16312124078ee5537b3/vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/ConditionalFormattingOnCellDeletionTest.java#L19)):*
>         spreadsheetPage = headerPage.loadFile("conditional_formatting_with_formula_on_second_sheet.xlsx", this);

* this line could be part of the test since other test probably would use a different file


>         this.spreadsheetPage.selectSheetAt(1);

* sheet is already selected in file

* also unless I missed something `setDebug(true)` is not needed

that would make the override of setUp not needed anymore

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/503)*

**Comment by alvarezguille** [comment]
*[vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/ConditionalFormattingOnCellDeletionTest.java, line 24 at r3](https://reviewable.io:443/reviews/vaadin/spreadsheet/503#-KhMmU7nZhNYJgFeCIwE:-KhMmU7nZhNYJgFeCIwF:b-2tphpb) ([raw file](https://github.com/vaadin/spreadsheet/blob/66c122733252bda50e81d16312124078ee5537b3/vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/ConditionalFormattingOnCellDeletionTest.java#L24)):*
>     public void deletionHandler_SpreadsheetWithDeletionFixture_deleteSingleCellFailsWhenHandlerReturnsFalse

the test method name could be more descriptive
something like `conditionalFormatting_deleteCell_formattingApplied` could work better IMO
the basic idea is from: http://osherove.com/blog/2005/4/3/naming-standards-for-unit-tests.html

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/503)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 3 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/503)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/503)*

**Pull request merged**
