### PR TITLE
Fix left cell border disappear with conditional formatting (#304)

### PR DESCRIPTION
**Pull request by MTzukanov**
Fixes: https://github.com/vaadin/spreadsheet/issues/304
https://github.com/tagetik/tagetik-2017-spreadsheet/issues/39

This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/530)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Reviewed 1 of 2 files at r8, 3 of 5 files at r9.
Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/530)*

**Comment by alvarezguille** [comment]
Left and top borders still disappear when un-doing a change. 

To reproduce:
* open `conditional_formatting_with_formula_on_second_sheet.xlsx`
* edit/delete `D15` content
* undo last action with `ctrl+z`.

Top and left border of C14 are disappear.

**Comment by MTzukanov** [comment]
I found another issue related to undo: if you put "borderless" into D14, undo, put something into D15 which is not "borderless", the bottom border of D14 is not correct.

Added tests for these issues.

**Comment by rolfsmeds** [comment]
Closing as stale.

**Pull request closed without merging**
