### PR TITLE
Force redraw of column and line headers on scroll (#262)

### PR DESCRIPTION
**Pull request by thinwire**
Change-Id: I8326909f4ecf379968de02e72c67781aaa5b324d

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/454)

### CODE REVIEW

**Comment by rogozinds** [comment]
Add test

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/454#-:-Kaat8zSatclzczF7HAN:bfv0pna)*

**Comment by rogozinds** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java, line 2912 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/454#-KaatQynramaLPxJ6k37:-KaatQynramaLPxJ6k38:bk3kp1c) ([raw file](https://github.com/vaadin/spreadsheet/blob/4bd5e8b7179983fee14aaea259a9a471fd4119f4/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java#L2912)):*
>     resetRowHeaders();
This should be handled in  the call of handleVerticalScrollDown(scrollTop); or handleVerticalScrollUp(scrollTop);
That's not a good idea to call reset everywhere, it can cause performance issues later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/454)*

**Comment by rogozinds** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/454)*

**Comment by rogozinds** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java, line 2912 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/454#-KaatQynramaLPxJ6k37:-Kcb02vFpjlBMhoN6DGE:b-smv1db) ([raw file](https://github.com/vaadin/spreadsheet/blob/4bd5e8b7179983fee14aaea259a9a471fd4119f4/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java#L2912)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

>     resetRowHeaders();
This should be handled in  the call of handleVerticalScrollDown(scrollTop); or handleVerticalScrollUp(scrollTop);
That's not a good idea to call reset everywhere, it can cause performance issues later.
</blockquote></details>

What about this one?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/454)*

**Comment by rogozinds** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/454)*

**Comment by thinwire** [comment]
*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java, line 2912 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/454#-KaatQynramaLPxJ6k37:-KcwnPAcD8ssaylOMSVF:b-8mfxwq) ([raw file](https://github.com/vaadin/spreadsheet/blob/4bd5e8b7179983fee14aaea259a9a471fd4119f4/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java#L2912)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

What about this one?
</blockquote></details>

Yeah I'll just add the test for now. Manual testing indicates that this change has a very minimal performance impact.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/454)*

**Comment by thinwire** [comment]
OK, pushed a test and reference screenshots. IE11 refuses to click buttons (too slow?) so not included.

**Comment by rogozinds** [comment]
Review status: 2 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-spreadsheet-charts/src/test/java/com/vaadin/spreadsheet/charts/interactiontests/ScrollTBTest.java, line 10 at r2](https://reviewable.io:443/reviews/vaadin/spreadsheet/454#-Kd-ciqn_YntE9CaJsT5:-Kd-ciqn_YntE9CaJsT6:bnqpses) ([raw file](https://github.com/vaadin/spreadsheet/blob/a8d48aa8b95fc3daa94bdb5fbed8ad3361ee6ab5/vaadin-spreadsheet-charts/src/test/java/com/vaadin/spreadsheet/charts/interactiontests/ScrollTBTest.java#L10)):*
> import com.vaadin.testbench.annotations.RunLocally;
Remove

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java, line 2912 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/454#-KaatQynramaLPxJ6k37:-Kd-dh_XdzJKcrCKCNn2:b-497su7) ([raw file](https://github.com/vaadin/spreadsheet/blob/4bd5e8b7179983fee14aaea259a9a471fd4119f4/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java#L2912)):*
<details><summary><i>Previously, thinwire (Patrik Lindström) wrote…</i></summary><blockquote>

Yeah I'll just add the test for now. Manual testing indicates that this change has a very minimal performance impact.
</blockquote></details>

In this particular case may be, but if we will fix all the logic and flow issues with calling redraw, it will be a hell. It's already a hell, but it will get worse.
Sorry, I first said that would be ok, but then I've looked in the code and seen that
"This should be handled in the call of handleVerticalScrollDown(scrollTop); or handleVerticalScrollUp(scrollTop);"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/454)*

**Comment by thinwire** [comment]
Well? We're not resetting both column and row headers now, just the applicable ones. The old partial update code has also been removed - it was broken anyway.

**Comment by rogozinds** [comment]
Reviewed 5 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-spreadsheet-charts/src/test/java/com/vaadin/spreadsheet/charts/interactiontests/ScrollTBTest.java, line 10 at r2](https://reviewable.io:443/reviews/vaadin/spreadsheet/454#-Kd-ciqn_YntE9CaJsT5:-KdVyFFY2YWF9g5P8xmq:bfiqlb6) ([raw file](https://github.com/vaadin/spreadsheet/blob/a8d48aa8b95fc3daa94bdb5fbed8ad3361ee6ab5/vaadin-spreadsheet-charts/src/test/java/com/vaadin/spreadsheet/charts/interactiontests/ScrollTBTest.java#L10)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

> import com.vaadin.testbench.annotations.RunLocally;
Remove
</blockquote></details>

Not fixed

---

*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java, line 3229 at r3](https://reviewable.io:443/reviews/vaadin/spreadsheet/454#-KdV4vu5murzqOFPnJXc:-KdV4vu6_isgWu5nnEcv:bwdxf73) ([raw file](https://github.com/vaadin/spreadsheet/blob/5baaee8889a38034accb601336106cd34dc6d9f8/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java#L3229)):*
<details><summary><i alt="summary">Quoted 34 lines of code…</i></summary>
>             while (move + add > 0) {
>                 DivElement header;
>                 if (move > 0) {
>                     move--;
>                     header = colHeaders.remove(colHeaders.size() - 1);
>                     header.setInnerHTML(actionHandler
>                             .getColHeader(firstColumnIndex + (move + add))
>                             + createHeaderDNDHTML());
>                     header.setClassName("ch col"
>                             + Integer.toString(firstColumnIndex + (move + add)));
>                     if (selectedColHeaderIndexes.contains(firstColumnIndex
>                             + (move + add))) {
>                         header.addClassName(SELECTED_COLUMN_HEADER_CLASSNAME);
>                     }
>                 } else {
>                     add--;
>                     header = Document.get().createDivElement();
>                     header.setInnerHTML(actionHandler
>                             .getColHeader(firstColumnIndex + add)
>                             + createHeaderDNDHTML());
>                     header.setClassName("ch col"
>                             + Integer.toString(firstColumnIndex + add));
>                     if (selectedColHeaderIndexes.contains(firstColumnIndex
>                             + add)) {
>                         header.addClassName(SELECTED_COLUMN_HEADER_CLASSNAME);
>                     }
>                     topRightPane.appendChild(header);
>                 }
>                 colHeaders.add(0, header);
>             }
>             while (colHeaders.size() > (lastColumnIndex - firstColumnIndex + 1)) {
>                 colHeaders.remove(colHeaders.size() - 1).removeFromParent();
>             }
>         }</details>


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/454)*

**Comment by thinwire** [comment]
*[vaadin-spreadsheet-charts/src/test/java/com/vaadin/spreadsheet/charts/interactiontests/ScrollTBTest.java, line 10 at r2](https://reviewable.io:443/reviews/vaadin/spreadsheet/454#-Kd-ciqn_YntE9CaJsT5:-KdW1HVJOXfxIgS7ZFz2:bvm575d) ([raw file](https://github.com/vaadin/spreadsheet/blob/a8d48aa8b95fc3daa94bdb5fbed8ad3361ee6ab5/vaadin-spreadsheet-charts/src/test/java/com/vaadin/spreadsheet/charts/interactiontests/ScrollTBTest.java#L10)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

Not fixed
</blockquote></details>

Pretty sure I removed that, must've been some kind of rebase glitch

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/454)*

**Comment by thinwire** [comment]
*[vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java, line 3229 at r3](https://reviewable.io:443/reviews/vaadin/spreadsheet/454#-KdV4vu5murzqOFPnJXc:-KdW1aCDREciOczYmXSu:b3kre) ([raw file](https://github.com/vaadin/spreadsheet/blob/5baaee8889a38034accb601336106cd34dc6d9f8/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java#L3229)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

>             while (move + add > 0) {
>                 DivElement header;
>                 if (move > 0) {
>                     move--;
>                     header = colHeaders.remove(colHeaders.size() - 1);
>                     header.setInnerHTML(actionHandler
>                             .getColHeader(firstColumnIndex + (move + add))
>                             + createHeaderDNDHTML());
>                     header.setClassName("ch col"
>                             + Integer.toString(firstColumnIndex + (move + add)));
>                     if (selectedColHeaderIndexes.contains(firstColumnIndex
>                             + (move + add))) {
>                         header.addClassName(SELECTED_COLUMN_HEADER_CLASSNAME);
>                     }
>                 } else {
>                     add--;
>                     header = Document.get().createDivElement();
>                     header.setInnerHTML(actionHandler
>                             .getColHeader(firstColumnIndex + add)
>                             + createHeaderDNDHTML());
>                     header.setClassName("ch col"
>                             + Integer.toString(firstColumnIndex + add));
>                     if (selectedColHeaderIndexes.contains(firstColumnIndex
>                             + add)) {
>                         header.addClassName(SELECTED_COLUMN_HEADER_CLASSNAME);
>                     }
>                     topRightPane.appendChild(header);
>                 }
>                 colHeaders.add(0, header);
>             }
>             while (colHeaders.size() > (lastColumnIndex - firstColumnIndex + 1)) {
>                 colHeaders.remove(colHeaders.size() - 1).removeFromParent();
>             }
>         }

</blockquote></details>

?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/454)*

**Comment by thinwire** [comment]
Removed RunLocally import

**Comment by rogozinds** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/454#-:-KdW3qj9mg_e2AOC2gl9:bnfp4nl)*

**Pull request merged**
