### PR TITLE
Fix #484, read/honor Excel defined explicit chart axis max/min values.

### LINKED ISSUE #484: Charts don't honor Excel configured axis min/max values
This can result in misleading charts that magnify value fluctuations by reducing the axis range to only the variation range of the data.  For example, if all values are between 950,000 and 1,050,000 units, the graph currently will display a range of about 200,000 units, making variations look quite large, when in fact they are all within 5% of the median.  We explicitly set the Y axis minimum in Excel to 0 to accurately display this, but Vaadin Spreadsheet Charts doesn't carry over that setting.

It is found in the CTValAx or CTCatAx getScaling().getMin.getVal() value.  You need to check scaling != null and scaling.isSetMin() first, to avoid NPEs.

### PR DESCRIPTION
**Pull request by WoozyG**
Fix for #484 

Note this only handles numeric axis ranges for now, as I can't yet see
how to tell if the stored double is a date or not.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/496)

### CODE REVIEW

**Comment by rogozinds** [comment]
Can you please add a test.
Add a test for the case if Axis has Date values.

**Comment by WoozyG** [comment]
I've never used TestBench - is it licensed as part of ProTools, or do I need a different subscription for that?  I'm out the next 10 days, so I won't be able to take a look at the docs and examples to get started for a couple of weeks.

If I can come up with a sample that just uses POI and the server-side configuration conversion code, is that sufficient?  I might be able to do that tomorrow before I leave.

**Comment by alvarezguille** [comment]
@WoozyG TestBench is part of Pro Tools Subscription yes. As it was mentioned before for some cases that it's just configuration reading it's ok to have just JUnit test like in #499, in other cases like when the interaction in client is needed TestBench tests are really handy like in the case of #504.

**Comment by WoozyG** [comment]
This fix only handles numeric axes.  Date axes are stored independently in the XLSX format, and served by OOXML as `poiChart.getCTChart().getPlotArea().getDateAxList()` which is distinct from `getCatAxList()`, `getSerAxList()`, and `getValAxList()`.

The OOXML structure is rather poor IMHO when it comes to charts, and POI has never had anyone add a good semantic layer to consolidate the different but nearly identical structures for different parts of charts.

I'd be willing to add that to POI, since it would help both my project and Vaadin, if Vaadin folks would use it and provide input on the most useful design strategy.

In the mean time, I can add a unit test to this PR that just tests numeric category series.  My sample that exposed this used years, which were defined as integer doubles in the Excel file, not year formatted dates.

**Comment by alvarezguille** [comment]
Hi @WoozyG, can you enable write access to the origin branch?

>In the the right sidebar of your pull request, select Allow edits from maintainers.

That would allow us to rebase it and fix some tab characters before merging

**Comment by WoozyG** [comment]
Done.  Haven't used GitHub much, didn't notice that.

**Comment by alvarezguille** [comment]
Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/496)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/496)*

**Pull request merged**
