### PR TITLE
Correctly generate components to the right of a merged cell

### LINKED ISSUE #359: Spreadsheet.loadRangeComponents() misses the first cell to the right of a merged region
**Originally by _woozy_**

---

at the end of Spreadsheet.loadRangeComponents() there is this conditional:

```
if (region != null) {
    c = region.col2;
}
```

c is the column index, 0-based, but regions are 1-based.  This means if there is a custom editor component for the cell to the right of a merged region, this loop skips it.

The expression should be:

```
if (region != null) {
    c = region.col2 - 1;
}
```

---

 Imported from https://dev.vaadin.com/ issue #19968

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #359

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spreadsheet/411)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/junit/TestableUI.java, line 16 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/411#-KWqKqDJtoPmFddHC_DG:-KWqKqDJtoPmFddHC_DH:bjv1c0w) ([raw file](https://github.com/vaadin/spreadsheet/blob/09854876187a950c04b94dfe914f6ccfd62b8c59/vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/junit/TestableUI.java#L16)):*
> ```Java
> import com.vaadin.ui.UI;
> 
> public class TestableUI extends UI {
> ```

can we add some doc here? what/why/when to use?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/411)*

**Comment by rogozinds** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/junit/SpreadsheetCustomEditorsTest.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/411#-KWqp7C4htyNweZYmYAW:-KWqp7C4htyNweZYmYAX:b-c7sq5j) ([raw file](https://github.com/vaadin/spreadsheet/blob/09854876187a950c04b94dfe914f6ccfd62b8c59/vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/junit/SpreadsheetCustomEditorsTest.java#L34)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>         // X M M X
>         // m M M mm
>         // m M M mm
>         // X M M X
</details>
Can description what X , mm and M are.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/411)*

**Comment by Artur-** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/junit/SpreadsheetCustomEditorsTest.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/411#-KWqp7C4htyNweZYmYAW:-KWvZA4IN0q-2xEoiX9C:b-896fix) ([raw file](https://github.com/vaadin/spreadsheet/blob/06b6e58f2014c89bd2387e478965cf086da3b750/vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/junit/SpreadsheetCustomEditorsTest.java#L34)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary>
> >         // X M M X
> >         // m M M mm
> >         // m M M mm
> >         // X M M X
> Can description what X , mm and M are.
> 
</details>
Done.

---

*[vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/junit/TestableUI.java, line 16 at r1](https://reviewable.io:443/reviews/vaadin/spreadsheet/411#-KWqKqDJtoPmFddHC_DG:-KWvZ9NJ8r9Hag7j-hWB:b-896fix) ([raw file](https://github.com/vaadin/spreadsheet/blob/06b6e58f2014c89bd2387e478965cf086da3b750/vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/junit/TestableUI.java#L16)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary>
> can we add some doc here? what/why/when to use?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/411)*

**Comment by alvarezguille** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spreadsheet/411)*

**Pull request merged**
